Repository huggingface/transformers, pull requests merged in 2021-09, with the labels that each got.

#12292 Fix for the issue of device-id getting hardcoded for position-ids during Tracing for Flaubert
  src/transformers/models/flaubert/modeling_flaubert.py
Labels: WIP

#12290 Fix for the issue of device-id getting hardcoded for position-ids during Tracing for Distillbert
  src/transformers/models/distilbert/modeling_distilbert.py
Labels: WIP

#12287 Fix for the issue of device-id getting hardcoded for token_type_ids during Tracing for ConvBert
  src/transformers/models/convbert/modeling_convbert.py
Labels: WIP

#12886 Object detection pipeline
  docs/source/main_classes/pipelines.rst
  docs/source/model_doc/auto.rst
  src/transformers/__init__.py
  src/transformers/models/auto/__init__.py
  src/transformers/models/auto/feature_extraction_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/pipelines/__init__.py
  src/transformers/pipelines/object_detection.py
  src/transformers/utils/dummy_pt_objects.py
  tests/test_pipelines_object_detection.py
Labels: Core: Pipeline

#13514 separate model card git push from the rest
  docs/source/model_sharing.rst
  src/transformers/trainer.py
Labels: model card, work in progress, trainer

#13564 upgrade sentencepiece version
  examples/research_projects/lxmert/demo.ipynb
  examples/research_projects/movement-pruning/Saving_PruneBERT.ipynb
  examples/research_projects/visual_bert/demo.ipynb
  setup.py
  src/transformers/dependency_versions_table.py
Labels: Installation, dependencies
