Repository huggingface/transformers, pull requests merged in 2022-10, with the labels that each got.

#19271 Breakup export guide
  docs/source/en/_toctree.yml
  docs/source/en/serialization.mdx
  docs/source/en/torchscript.mdx
Labels: Documentation

#19360 Fix gather for metrics
  examples/pytorch/summarization/run_summarization_no_trainer.py
Labels: Examples, bug

#19124 Sharding fails in TF when absolute scope was modified if `.` in layer name
  src/transformers/modeling_tf_utils.py
  tests/test_modeling_tf_common.py
Labels: TensorFlow, Core: Modeling

#19623 Add doctest info in testingmdx
  docs/source/en/testing.mdx
Labels: Documentation

#19847 Small update to model addition guide
  docs/source/en/add_new_model.mdx
Labels: Documentation
