Repository huggingface/transformers, pull requests merged in 2022-02, with the labels that each got.

#15259 Update fine-tune docs
  docs/source/training.mdx
Labels: Documentation

#15165 Update tutorial docs
  docs/source/_toctree.yml
  docs/source/autoclass_tutorial.mdx
  docs/source/pipeline_tutorial.mdx
  docs/source/preprocessing.mdx
Labels: Documentation

#15489 Create a custom model guide
  docs/source/_toctree.yml
  docs/source/create_a_model.mdx
Labels: Documentation

#14656 [t5/t0/mt5 models] faster/leaner custom layer norm
  docs/source/model_doc/t5.mdx
  src/transformers/models/t5/modeling_t5.py
Labels: Performance, WIP

#13269 Add PLBart
  docs/source/_toctree.yml
  docs/source/index.mdx
  docs/source/model_doc/plbart.mdx
  docs/source/serialization.mdx
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/plbart/__init__.py
  src/transformers/models/plbart/configuration_plbart.py
  src/transformers/models/plbart/convert_plbart_original_checkpoint_to_torch.py
  src/transformers/models/plbart/modeling_plbart.py
  src/transformers/models/plbart/tokenization_plbart.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_sentencepiece_objects.py
  tests/test_modeling_plbart.py
  tests/test_tokenization_plbart.py
  utils/check_repo.py
Labels: WIP
