Repository huggingface/transformers, pull requests merged in 2022-04, with the labels that each got.

#14934 [benchmark tool] trainer-benchmark.py
  scripts/benchmark/trainer-benchmark.py
Labels: Performance, WIP

#16528 Update summary of the tasks
  docs/source/en/task_summary.mdx
Labels: Documentation

#16617 Update no_trainer scripts with new Accelerate functionalities
  examples/pytorch/language-modeling/run_clm_no_trainer.py
  examples/pytorch/language-modeling/run_mlm_no_trainer.py
  examples/pytorch/multiple-choice/run_swag_no_trainer.py
  examples/pytorch/question-answering/run_qa_beam_search_no_trainer.py
  examples/pytorch/question-answering/run_qa_no_trainer.py
  examples/pytorch/summarization/run_summarization_no_trainer.py
  examples/pytorch/text-classification/run_glue_no_trainer.py
  examples/pytorch/token-classification/run_ner_no_trainer.py
  examples/pytorch/translation/run_translation_no_trainer.py
Labels: PyTorch, External, Examples

#16633 Update audio examples with MInDS-14
  docs/source/en/preprocessing.mdx
  docs/source/en/quicktour.mdx
  docs/source/en/tasks/asr.mdx
  docs/source/en/tasks/audio_classification.mdx
Labels: Documentation

#16703 Don't push checkpoints to hub in `no_trainer` scripts
  examples/pytorch/language-modeling/run_clm_no_trainer.py
  examples/pytorch/language-modeling/run_mlm_no_trainer.py
  examples/pytorch/multiple-choice/run_swag_no_trainer.py
  examples/pytorch/question-answering/run_qa_beam_search_no_trainer.py
  examples/pytorch/question-answering/run_qa_no_trainer.py
  examples/pytorch/summarization/run_summarization_no_trainer.py
  examples/pytorch/text-classification/run_glue_no_trainer.py
  examples/pytorch/token-classification/run_ner_no_trainer.py
  examples/pytorch/translation/run_translation_no_trainer.py
Labels: PyTorch, External, Examples

#16669 Fix example logs repeating themselves
  examples/flax/test_flax_examples.py
  examples/pytorch/test_accelerate_examples.py
  examples/pytorch/test_pytorch_examples.py
  examples/pytorch/test_xla_examples.py
  examples/research_projects/rag/_test_finetune_rag.py
Labels: Examples, bug

#10638 Fix decoding score comparison when using logits processors or warpers
  src/transformers/generation_logits_process.py
  src/transformers/generation_utils.py
  src/transformers/models/rag/modeling_rag.py
  tests/generation/test_generation_logits_process.py
Labels: WIP

#16783 Fix nightly CI Accelerate failures
  .circleci/config.yml
Labels: Tests, Examples, bug

#16717 [deepspeed / m2m_100] make deepspeed zero-3 work with layerdrop
  src/transformers/models/m2m_100/modeling_m2m_100.py
Labels: DeepSpeed

#15622 Add support for bitsandbytes
  src/transformers/testing_utils.py
  src/transformers/trainer.py
  src/transformers/training_args.py
  src/transformers/utils/__init__.py
  src/transformers/utils/import_utils.py
  tests/extended/test_trainer_ext.py
  tests/trainer/test_trainer.py
Labels: WIP

#16865 Fix multiproc metrics in no_trainer examples
  examples/pytorch/image-classification/run_image_classification_no_trainer.py
  examples/pytorch/multiple-choice/run_swag_no_trainer.py
  examples/pytorch/semantic-segmentation/run_semantic_segmentation_no_trainer.py
  examples/pytorch/summarization/run_summarization_no_trainer.py
  examples/pytorch/text-classification/run_glue_no_trainer.py
  examples/pytorch/token-classification/run_ner_no_trainer.py
  examples/pytorch/translation/run_translation_no_trainer.py
Labels: Examples, bug

#16968 Fixup no_trainer save logic
  examples/pytorch/image-classification/run_image_classification_no_trainer.py
  examples/pytorch/language-modeling/run_clm_no_trainer.py
  examples/pytorch/language-modeling/run_mlm_no_trainer.py
  examples/pytorch/multiple-choice/run_swag_no_trainer.py
  examples/pytorch/question-answering/run_qa_beam_search_no_trainer.py
  examples/pytorch/question-answering/run_qa_no_trainer.py
  examples/pytorch/semantic-segmentation/run_semantic_segmentation_no_trainer.py
  examples/pytorch/speech-pretraining/run_wav2vec2_pretraining_no_trainer.py
  examples/pytorch/summarization/run_summarization_no_trainer.py
  examples/pytorch/text-classification/run_glue_no_trainer.py
  examples/pytorch/token-classification/run_ner_no_trainer.py
  examples/pytorch/translation/run_translation_no_trainer.py
Labels: PyTorch, Examples

#16996 Fix savedir for by epoch in translation example
  examples/pytorch/translation/run_translation_no_trainer.py
Labels: Examples

#16999 Refactor all require decorators to use skipUnless when possible
  src/transformers/testing_utils.py
Labels: Tests, cleanup
