Repository huggingface/transformers, pull requests merged in 2022-07, with the labels that each got.

#17427 Add TF ResNet model
  docs/source/en/index.mdx
  docs/source/en/model_doc/resnet.mdx
  src/transformers/__init__.py
  src/transformers/modeling_tf_outputs.py
  src/transformers/models/auto/modeling_tf_auto.py
  src/transformers/models/resnet/__init__.py
  src/transformers/models/resnet/modeling_tf_resnet.py
  src/transformers/utils/dummy_tf_objects.py
  tests/models/resnet/test_modeling_tf_resnet.py
  utils/documentation_tests.txt
Labels: New model

#18011 sort list of models in docs table-of-contents
  docs/source/en/_toctree.yml
Labels: Documentation

#18115 Add custom config to quicktour
  docs/source/en/quicktour.mdx
Labels: Documentation

#18242 Fix `no_trainer` CI
  examples/pytorch/test_accelerate_examples.py
  src/transformers/testing_utils.py
Labels: Tests, Examples, bug

#18324 Update feature extractor docs
  docs/source/en/main_classes/feature_extractor.mdx
Labels: Documentation
