Repository huggingface/transformers, pull requests merged in 2022-01, with the labels that each got.

#15001 Fix TFEncoderDecoder labels handling #14357
  src/transformers/models/encoder_decoder/modeling_tf_encoder_decoder.py
Labels: TensorFlow

#13292 Add REALM
  README.md
  README_ko.md
  README_zh-hans.md
  README_zh-hant.md
  docs/source/_toctree.yml
  docs/source/index.mdx
  docs/source/model_doc/realm.mdx
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/realm/__init__.py
  src/transformers/models/realm/configuration_realm.py
  src/transformers/models/realm/modeling_realm.py
  src/transformers/models/realm/retrieval_realm.py
  src/transformers/models/realm/tokenization_realm.py
  src/transformers/utils/dummy_pt_objects.py
  tests/test_modeling_realm.py
  tests/test_retrieval_realm.py
  tests/test_tokenization_realm.py
  utils/check_repo.py
Labels: WIP

#13815 [FLAX] glue training example refactor
  examples/flax/test_examples.py
  examples/flax/text-classification/README.md
  examples/flax/text-classification/run_flax_glue.py
Labels: WIP

#15263 Add 🤗 Accelerate tutorial
  docs/source/_toctree.yml
  docs/source/accelerate.mdx
Labels: Documentation

#14876 Add XGLM models
  README.md
  README_ko.md
  README_zh-hans.md
  README_zh-hant.md
  docs/source/_toctree.yml
  docs/source/index.mdx
  docs/source/model_doc/xglm.mdx
  src/transformers/__init__.py
  src/transformers/convert_slow_tokenizer.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/modeling_flax_auto.py
  src/transformers/models/xglm/__init__.py
  src/transformers/models/xglm/configuration_xglm.py
  src/transformers/models/xglm/modeling_flax_xglm.py
  src/transformers/models/xglm/modeling_xglm.py
  src/transformers/models/xglm/tokenization_xglm.py
  src/transformers/models/xglm/tokenization_xglm_fast.py
  src/transformers/utils/dummy_flax_objects.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_sentencepiece_objects.py
  src/transformers/utils/dummy_tokenizers_objects.py
  tests/test_modeling_flax_xglm.py
  tests/test_modeling_xglm.py
  tests/test_tokenization_xglm.py
  utils/check_repo.py
Labels: WIP

#15288 Update model share tutorial
  docs/source/_toctree.yml
  docs/source/model_sharing.mdx
Labels: Documentation

#15098 Get started docs
  docs/source/index.mdx
  docs/source/installation.mdx
  docs/source/quicktour.mdx
Labels: Documentation
