Repository huggingface/transformers, pull requests merged in 2022-08, with the labels that each got.

#18440 Fix model list
  docs/source/en/_toctree.yml
Labels: Documentation

#18489 Just re-reading the whole doc every couple of months 😬
  README.md
  docs/source/en/accelerate.mdx
  docs/source/en/model_sharing.mdx
  docs/source/en/perf_train_gpu_one.mdx
  docs/source/en/pipeline_tutorial.mdx
  docs/source/en/run_scripts.mdx
  docs/source/en/task_summary.mdx
  docs/source/es/accelerate.mdx
  docs/source/es/model_sharing.mdx
  docs/source/es/run_scripts.mdx
  docs/source/it/accelerate.mdx
  docs/source/it/model_sharing.mdx
  docs/source/it/run_scripts.mdx
  docs/source/pt/accelerate.mdx
  examples/legacy/pytorch-lightning/run_ner.sh
  examples/legacy/token-classification/README.md
  examples/legacy/token-classification/run.sh
  examples/pytorch/README.md
  examples/tensorflow/README.md
  valohai.yaml
Labels: Documentation

#18500 Update to use interlibrary links instead of Markdown
  docs/source/en/accelerate.mdx
Labels: Documentation

#18498 Add example of multimodal usage to pipeline tutorial
  docs/source/en/pipeline_tutorial.mdx
Labels: Documentation

#18535 Update Metrics in docs with Evaluate
  docs/source/en/training.mdx
Labels: Documentation

#18548 Update documentation build section
  docs/source/en/pr_checks.mdx
Labels: Documentation

#18550 Update philosophy to include other preprocessing classes
  docs/source/en/philosophy.mdx
Labels: Documentation

#18419 Load sharded pt to flax
  src/transformers/modeling_flax_pytorch_utils.py
  src/transformers/modeling_flax_utils.py
  tests/test_modeling_flax_common.py
Labels: Core: Modeling, Flax

#18666 Add evaluate to examples requirements
  examples/pytorch/audio-classification/requirements.txt
  examples/pytorch/image-classification/requirements.txt
  examples/pytorch/language-modeling/requirements.txt
  examples/pytorch/multiple-choice/requirements.txt
  examples/pytorch/question-answering/requirements.txt
  examples/pytorch/semantic-segmentation/requirements.txt
  examples/pytorch/speech-pretraining/requirements.txt
  examples/pytorch/speech-recognition/requirements.txt
  examples/pytorch/summarization/requirements.txt
  examples/pytorch/text-classification/requirements.txt
  examples/pytorch/token-classification/requirements.txt
  examples/pytorch/translation/requirements.txt
Labels: Examples

#18668 Warn on TPUs when the custom optimizer and model device are not the same
  src/transformers/trainer.py
Labels: Distributed Training / Models, bug
