Repository huggingface/transformers, pull requests merged in 2022-03, with the labels that each got.

#15836 Inference for multilingual models
  docs/source/_toctree.yml
  docs/source/multilingual.mdx
Labels: Documentation

#15931 Update training scripts docs
  docs/source/_toctree.yml
  docs/source/examples.md
  docs/source/run_scripts.mdx
Labels: Documentation

#16001 Update troubleshoot guide
  docs/source/_toctree.yml
  docs/source/troubleshooting.mdx
Labels: Documentation

#15808 Audio/vision task guides
  docs/source/_toctree.yml
  docs/source/tasks/asr.mdx
  docs/source/tasks/audio_classification.mdx
  docs/source/tasks/image_classification.mdx
Labels: Documentation

#16093 [ZeRO] Fixes issue with embedding resize
  src/transformers/modeling_utils.py
Labels: DeepSpeed

#14569 [Deepspeed] add support for bf16 mode
  docs/source/main_classes/deepspeed.mdx
  examples/research_projects/wav2vec2/ds_config_wav2vec2_zero3.json
  setup.py
  src/transformers/deepspeed.py
  src/transformers/dependency_versions_table.py
  src/transformers/trainer.py
  tests/deepspeed/ds_config_zero2.json
  tests/deepspeed/ds_config_zero3.json
  tests/deepspeed/test_deepspeed.py
  tests/deepspeed/test_model_zoo.py
Labels: WIP

#16182 Fix links in guides
  docs/source/tasks/asr.mdx
  docs/source/tasks/audio_classification.mdx
  docs/source/tasks/image_classification.mdx
  docs/source/tasks/language_modeling.mdx
  docs/source/tasks/multiple_choice.mdx
  docs/source/tasks/question_answering.mdx
  docs/source/tasks/sequence_classification.mdx
  docs/source/tasks/summarization.mdx
  docs/source/tasks/token_classification.mdx
  docs/source/tasks/translation.mdx
Labels: Documentation

#16243 Update troubleshoot with more content
  docs/source/troubleshooting.mdx
Labels: Documentation

#16342 Adopt framework-specific blocks for content
  docs/source/_toctree.yml
  docs/source/model_sharing.mdx
  docs/source/tasks/asr.mdx
  docs/source/tasks/audio_classification.mdx
  docs/source/tasks/image_classification.mdx
  docs/source/tasks/language_modeling.mdx
  docs/source/tasks/multiple_choice.mdx
  docs/source/tasks/question_answering.mdx
  docs/source/tasks/sequence_classification.mdx
  docs/source/tasks/summarization.mdx
  docs/source/tasks/token_classification.mdx
  docs/source/tasks/translation.mdx
  docs/source/training.mdx
Labels: Documentation

#16369 Create concept guide section
  docs/source/_toctree.yml
  docs/source/create_a_model.mdx
  docs/source/custom_datasets.mdx
  docs/source/fast_tokenizers.mdx
  docs/source/index.mdx
  docs/source/pad_truncation.mdx
  docs/source/preprocessing.mdx
  docs/source/serialization.mdx
Labels: Documentation

#16496 Support reduce_bucket_size="auto" for deepspeed stages <3
  src/transformers/deepspeed.py
Labels: DeepSpeed
