Repository huggingface/transformers, pull requests merged in 2024-08, with the labels that each got.

#32080 Add codestral mamba2
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/mamba2.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/mamba2/__init__.py
  src/transformers/models/mamba2/configuration_mamba2.py
  src/transformers/models/mamba2/convert_mamba2_ssm_checkpoint_to_pytorch.py
  src/transformers/models/mamba2/modeling_mamba2.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/import_utils.py
  tests/models/mamba2/__init__.py
  tests/models/mamba2/test_modeling_mamba2.py
Labels: run-slow

#31735 Agents use grammar
  docs/source/en/agents.md
  src/transformers/agents/agents.py
  src/transformers/agents/llm_engine.py
  src/transformers/agents/prompts.py
  tests/agents/test_agents.py
Labels: Agents

#32137 Add Qwen2-Audio
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/qwen2_audio.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/qwen2_audio/__init__.py
  src/transformers/models/qwen2_audio/configuration_qwen2_audio.py
  src/transformers/models/qwen2_audio/modeling_qwen2_audio.py
  src/transformers/models/qwen2_audio/processing_qwen2_audio.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/qwen2_audio/__init__.py
  tests/models/qwen2_audio/test_modeling_qwen2_audio.py
  tests/models/qwen2_audio/test_processor_qwen2_audio.py
  utils/check_repo.py
  utils/check_table.py
Labels: Audio, run-slow

#32493 Fix generate with `inputs_embeds` as input
  src/transformers/models/codegen/modeling_codegen.py
  src/transformers/models/cohere/modeling_cohere.py
  src/transformers/models/dbrx/modeling_dbrx.py
  src/transformers/models/falcon/modeling_falcon.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/gemma2/modeling_gemma2.py
  src/transformers/models/gpt_neo/modeling_gpt_neo.py
  src/transformers/models/gpt_neox/modeling_gpt_neox.py
  src/transformers/models/gptj/modeling_gptj.py
  src/transformers/models/llama/modeling_llama.py
  src/transformers/models/nemotron/modeling_nemotron.py
  src/transformers/models/olmo/modeling_olmo.py
  src/transformers/models/persimmon/modeling_persimmon.py
  src/transformers/models/phi/modeling_phi.py
  src/transformers/models/phi3/modeling_phi3.py
  src/transformers/models/qwen2/modeling_qwen2.py
  src/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  src/transformers/models/stablelm/modeling_stablelm.py
  src/transformers/models/starcoder2/modeling_starcoder2.py
  tests/models/bart/test_modeling_bart.py
  tests/models/bert/test_modeling_bert.py
  tests/models/whisper/test_modeling_whisper.py
  tests/test_modeling_common.py
Labels: run-slow

#32487 Fix: FA2 with packed training
  src/transformers/modeling_flash_attention_utils.py
  src/transformers/models/phi3/modeling_phi3.py
  tests/models/whisper/test_modeling_whisper.py
  tests/test_modeling_common.py
Labels: run-slow

#32522 Fix sliding window attention used in Gemma2FlashAttention2
  src/transformers/models/gemma2/modeling_gemma2.py
Labels: run-slow

#30962 Expand inputs in processors for VLMs
  src/transformers/models/blip_2/configuration_blip_2.py
  src/transformers/models/blip_2/modeling_blip_2.py
  src/transformers/models/blip_2/processing_blip_2.py
  src/transformers/models/instructblip/configuration_instructblip.py
  src/transformers/models/instructblip/modeling_instructblip.py
  src/transformers/models/instructblip/processing_instructblip.py
  src/transformers/models/instructblipvideo/configuration_instructblipvideo.py
  src/transformers/models/instructblipvideo/diff_instructblipvideo.py
  src/transformers/models/instructblipvideo/modeling_instructblipvideo.py
  src/transformers/models/instructblipvideo/processing_instructblipvideo.py
  src/transformers/models/llava/configuration_llava.py
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava/processing_llava.py
  src/transformers/models/llava_next/configuration_llava_next.py
  src/transformers/models/llava_next/modeling_llava_next.py
  src/transformers/models/llava_next/processing_llava_next.py
  src/transformers/models/llava_next_video/configuration_llava_next_video.py
  src/transformers/models/llava_next_video/diff_llava_next_video.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/llava_next_video/processing_llava_next_video.py
  src/transformers/models/paligemma/configuration_paligemma.py
  src/transformers/models/paligemma/modeling_paligemma.py
  src/transformers/models/video_llava/configuration_video_llava.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/video_llava/processing_video_llava.py
  src/transformers/models/vipllava/configuration_vipllava.py
  src/transformers/models/vipllava/modeling_vipllava.py
  tests/models/blip_2/test_modeling_blip_2.py
  tests/models/instructblip/test_modeling_instructblip.py
  tests/models/instructblip/test_processor_instructblip.py
  tests/models/instructblipvideo/test_modeling_instructblipvideo.py
  tests/models/llava/test_modeling_llava.py
  tests/models/llava_next/test_modeling_llava_next.py
  tests/models/llava_next_video/test_modeling_llava_next_video.py
  tests/models/paligemma/test_modeling_paligemma.py
  tests/models/video_llava/test_modeling_video_llava.py
  tests/models/vipllava/test_modeling_vipllava.py
Labels: WIP, run-slow

#32126 Add Depth Anything V2 Metric models
  src/transformers/models/depth_anything/configuration_depth_anything.py
  src/transformers/models/depth_anything/convert_depth_anything_to_hf.py
  src/transformers/models/depth_anything/modeling_depth_anything.py
  tests/models/depth_anything/test_modeling_depth_anything.py
Labels: run-slow

#32306 Add TorchAOHfQuantizer
  docs/source/en/_toctree.yml
  docs/source/en/main_classes/quantization.md
  docs/source/en/quantization/overview.md
  docs/source/en/quantization/torchao.md
  src/transformers/__init__.py
  src/transformers/quantizers/auto.py
  src/transformers/quantizers/quantizer_torchao.py
  src/transformers/testing_utils.py
  src/transformers/utils/__init__.py
  src/transformers/utils/import_utils.py
  src/transformers/utils/quantization_config.py
  tests/quantization/torchao_integration/__init__.py
  tests/quantization/torchao_integration/test_torchao.py
Labels: Quantization

#32417 VLMs: small clean-up for cache class
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava_next/modeling_llava_next.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/vipllava/modeling_vipllava.py
Labels: run-slow

#32520 [tests] make test_sdpa_equivalence device-agnostic
  tests/models/gemma/test_modeling_gemma.py
Labels: run-slow

#31960 Add Flax Dinov2
  docs/source/en/index.md
  docs/source/en/model_doc/dinov2.md
  src/transformers/__init__.py
  src/transformers/models/auto/modeling_flax_auto.py
  src/transformers/models/dinov2/__init__.py
  src/transformers/models/dinov2/modeling_flax_dinov2.py
  src/transformers/utils/dummy_flax_objects.py
  tests/models/dinov2/test_modeling_flax_dinov2.py
  utils/check_docstrings.py
Labels: run-slow

#31494 Add Descript-Audio-Codec model
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/dac.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/feature_extraction_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/dac/__init__.py
  src/transformers/models/dac/configuration_dac.py
  src/transformers/models/dac/convert_dac_checkpoint.py
  src/transformers/models/dac/feature_extraction_dac.py
  src/transformers/models/dac/modeling_dac.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/dac/__init__.py
  tests/models/dac/test_feature_extraction_dac.py
  tests/models/dac/test_modeling_dac.py
Labels: Audio, run-slow

#32519 [tests] make `test_sdpa_can_compile_dynamic` device-agnostic
  tests/test_modeling_common.py
Labels: run-slow

#32887 Replace `.norm()` with decomposed version for CLIP executorch export
  src/transformers/models/clip/modeling_clip.py
Labels: Vision, run-slow, ExecuTorch

#31296 fix: [whisper] don't overwrite GenerationConfig's `return_timestamps` when `return_timestamps` is not passed to `generate` function
  src/transformers/models/whisper/generation_whisper.py
Labels: Generation, Audio

#32250 Jamba: update integration tests
  tests/models/jamba/test_modeling_jamba.py
Labels: run-slow

#32840 [run_slow] idefics2
  tests/models/idefics2/test_modeling_idefics2.py
Labels: run-slow

#32318 support qwen2-vl
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/qwen2_vl.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/qwen2_vl/__init__.py
  src/transformers/models/qwen2_vl/configuration_qwen2_vl.py
  src/transformers/models/qwen2_vl/image_processing_qwen2_vl.py
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
  src/transformers/models/qwen2_vl/processing_qwen2_vl.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/models/qwen2_vl/__init__.py
  tests/models/qwen2_vl/test_image_processing_qwen2_vl.py
  tests/models/qwen2_vl/test_modeling_qwen2_vl.py
  utils/check_config_attributes.py
  utils/check_repo.py
Labels: New model

#32115 Update stateful_callbacks state before saving checkpoint
  src/transformers/trainer.py
Labels: trainer

#29261 🚨 Add Blip2ForImageTextRetrieval
  docs/source/en/model_doc/blip-2.md
  src/transformers/__init__.py
  src/transformers/models/altclip/modeling_altclip.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/blip_2/__init__.py
  src/transformers/models/blip_2/configuration_blip_2.py
  src/transformers/models/blip_2/convert_blip_2_original_to_pytorch.py
  src/transformers/models/blip_2/modeling_blip_2.py
  src/transformers/models/clap/modeling_clap.py
  src/transformers/models/clip/modeling_clip.py
  src/transformers/models/clipseg/modeling_clipseg.py
  src/transformers/models/siglip/modeling_siglip.py
  src/transformers/pipelines/zero_shot_image_classification.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/blip_2/test_modeling_blip_2.py
  tests/pipelines/test_pipelines_zero_shot_image_classification.py
  utils/check_repo.py
Labels: run-slow

#31502 Granite language models
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/granite.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/granite/__init__.py
  src/transformers/models/granite/configuration_granite.py
  src/transformers/models/granite/modeling_granite.py
  src/transformers/pytorch_utils.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/granite/__init__.py
  tests/models/granite/test_modeling_granite.py
  utils/check_config_docstrings.py
Labels: New model, run-slow

#32524 pass module to Params4bit.from_prequantized to ensure quant_state
  src/transformers/quantizers/quantizer_bnb_4bit.py
Labels: Quantization, PyTorch FSDP

#33218 Create local Transformers Engine
  docs/source/en/agents.md
  docs/source/en/main_classes/agent.md
  docs/source/ko/main_classes/agent.md
  src/transformers/__init__.py
  src/transformers/agents/__init__.py
  src/transformers/agents/agents.py
  src/transformers/agents/llm_engine.py
Labels: Agents
