Repository huggingface/transformers, pull requests merged in 2024-11, with the labels that each got.

#34531 Fix #34494 assistant tokens when truncated
  src/transformers/tokenization_utils_base.py
  tests/models/layoutlmv2/test_tokenization_layoutlmv2.py
  tests/models/layoutlmv3/test_tokenization_layoutlmv3.py
  tests/models/layoutxlm/test_tokenization_layoutxlm.py
  tests/models/markuplm/test_tokenization_markuplm.py
  tests/models/tapas/test_tokenization_tapas.py
  tests/models/udop/test_tokenization_udop.py
  tests/test_tokenization_common.py
Labels: bug, Chat Template

#34549 Agents: Small fixes in streaming to gradio + add tests
  src/transformers/agents/agents.py
  src/transformers/agents/monitoring.py
  src/transformers/agents/python_interpreter.py
  src/transformers/agents/tools.py
  tests/agents/test_monitoring.py
Labels: Agents

#34762 Fix callback key name
  docs/source/en/trainer.md
Labels: Documentation, trainer

#34757 fix: Wrong task mentioned in docs
  docs/source/en/tasks_explained.md
Labels: Documentation

#34687 Allow handling files as args for a tool created with Tool.from_space
  src/transformers/agents/tools.py
Labels: Agents

#34393 🚨🚨🚨 fix(Mask2Former): torch export 🚨🚨🚨
  src/transformers/models/mask2former/modeling_mask2former.py
  tests/models/mask2former/test_modeling_mask2former.py
Labels: run-slow, ExecuTorch

#34523 Add do_convert_rgb to vit
  src/transformers/models/vit/image_processing_vit.py
  src/transformers/models/vit/image_processing_vit_fast.py
Labels: Vision, Processing

#34728 fix crash in tiiuae/falcon-11B-vlm image-to-text generation
  src/transformers/models/falcon/modeling_falcon.py
Labels: Vision, Multimodal

#22105 [`Deberta/Deberta-v2`] Refactor code base to support compile, export, and fix LLM
  src/transformers/models/deberta/configuration_deberta.py
  src/transformers/models/deberta/modeling_deberta.py
  src/transformers/models/deberta_v2/configuration_deberta_v2.py
  src/transformers/models/deberta_v2/modeling_deberta_v2.py
  src/transformers/models/sew_d/modeling_sew_d.py
  tests/models/deberta/test_modeling_deberta.py
  tests/models/deberta/test_modeling_tf_deberta.py
  tests/models/deberta_v2/test_modeling_deberta_v2.py
  tests/models/deberta_v2/test_modeling_tf_deberta_v2.py
  tests/test_modeling_common.py
Labels: WIP

#34111 [Whisper] Fix whisper integration tests
  tests/models/whisper/test_modeling_whisper.py
Labels: run-slow

#34890 Fix `save_pretrained` for partially offloaded models
  src/transformers/modeling_utils.py
Labels: bug, Accelerate

#34568 🚨🚨🚨 Changed DINOv2Config default patch size to 14
  src/transformers/models/dinov2/configuration_dinov2.py
Labels: bug

#34587 🚨🚨🚨 Uniformize kwargs for TrOCR Processor
  src/transformers/models/trocr/processing_trocr.py
  tests/models/trocr/test_processor_trocr.py
Labels: Vision, Multimodal, Processing
