Repository huggingface/transformers, pull requests merged in 2024-05, with the labels that each got.

#29721 Fix llava half precision and autocast issues
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava_next/modeling_llava_next.py
  tests/models/llava/test_modeling_llava.py
  tests/models/llava_next/test_modeling_llava_next.py
Labels: run-slow

#30566 🚨 Update image_processing_vitmatte.py
  src/transformers/models/vitmatte/image_processing_vitmatte.py
  tests/models/vitmatte/test_image_processing_vitmatte.py
Labels: run-slow

#30612 Fix CI after #30410
  src/transformers/models/blenderbot/modeling_blenderbot.py
Labels: run-slow

#30387 Reboot Agents
  conftest.py
  docs/source/en/_toctree.yml
  docs/source/en/agents.md
  docs/source/en/custom_tools.md
  docs/source/en/main_classes/agent.md
  docs/source/en/transformers_agents.md
  docs/source/ja/custom_tools.md
  docs/source/ja/main_classes/agent.md
  docs/source/ko/custom_tools.md
  docs/source/zh/main_classes/agent.md
  src/transformers/__init__.py
  src/transformers/agents/__init__.py
  src/transformers/agents/agent_types.py
  src/transformers/agents/agents.py
  src/transformers/agents/default_tools.py
  src/transformers/agents/document_question_answering.py
  src/transformers/agents/evaluate_agent.py
  src/transformers/agents/image_question_answering.py
  src/transformers/agents/llm_engine.py
  src/transformers/agents/prompts.py
  src/transformers/agents/python_interpreter.py
  src/transformers/agents/speech_to_text.py
  src/transformers/agents/text_to_speech.py
  src/transformers/agents/tools.py
  src/transformers/agents/translation.py
  src/transformers/testing_utils.py
  src/transformers/tools/agents.py
  src/transformers/tools/image_captioning.py
  src/transformers/tools/image_segmentation.py
  src/transformers/tools/prompts.py
  src/transformers/tools/python_interpreter.py
  src/transformers/tools/text_classification.py
  src/transformers/tools/text_question_answering.py
  src/transformers/tools/text_summarization.py
  src/transformers/utils/import_utils.py
  tests/agents/__init__.py
  tests/agents/test_agent_types.py
  tests/agents/test_agents.py
  tests/agents/test_document_question_answering.py
  tests/agents/test_final_answer.py
  tests/agents/test_image_question_answering.py
  tests/agents/test_python_interpreter.py
  tests/agents/test_speech_to_text.py
  tests/agents/test_text_to_speech.py
  tests/agents/test_tools_common.py
  tests/agents/test_translation.py
  tests/tools/test_image_captioning.py
  tests/tools/test_image_segmentation.py
  tests/tools/test_python_interpreter.py
  tests/tools/test_text_classification.py
  tests/tools/test_text_question_answering.py
  tests/tools/test_text_summarization.py
  tests/tools/test_tools_common.py
  tests/tools/test_translation.py
  utils/not_doctested.txt
Labels: Agents

#29733 Add Video Llava
  README_fr.md
  README_te.md
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/video_llava.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/image_utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/video_llava/__init__.py
  src/transformers/models/video_llava/configuration_video_llava.py
  src/transformers/models/video_llava/convert_video_llava_weights_to_hf.py
  src/transformers/models/video_llava/image_processing_video_llava.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/video_llava/processing_video_llava.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/video_llava/__init__.py
  tests/models/video_llava/test_image_processing_video_llava.py
  tests/models/video_llava/test_modeling_video_llava.py
  tests/test_modeling_common.py
Labels: New model

#30555 add sdpa to ViT [follow up of #29325]
  docs/source/en/model_doc/audio-spectrogram-transformer.md
  docs/source/en/model_doc/deit.md
  docs/source/en/model_doc/videomae.md
  docs/source/en/model_doc/vit.md
  docs/source/en/model_doc/vit_hybrid.md
  docs/source/en/model_doc/vit_mae.md
  docs/source/en/model_doc/vit_msn.md
  docs/source/en/model_doc/yolos.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/audio_spectrogram_transformer/modeling_audio_spectrogram_transformer.py
  src/transformers/models/deit/modeling_deit.py
  src/transformers/models/videomae/modeling_videomae.py
  src/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py
  src/transformers/models/vit/modeling_vit.py
  src/transformers/models/vit_hybrid/modeling_vit_hybrid.py
  src/transformers/models/vit_mae/modeling_vit_mae.py
  src/transformers/models/vit_msn/modeling_vit_msn.py
  src/transformers/models/yolos/modeling_yolos.py
  tests/models/audio_spectrogram_transformer/test_modeling_audio_spectrogram_transformer.py
  tests/models/deit/test_modeling_deit.py
  tests/models/deit/test_modeling_tf_deit.py
  tests/models/videomae/test_modeling_videomae.py
  tests/models/vision_encoder_decoder/test_modeling_tf_vision_encoder_decoder.py
  tests/models/vit/test_modeling_flax_vit.py
  tests/models/vit/test_modeling_tf_vit.py
  tests/models/vit/test_modeling_vit.py
  tests/models/vit_hybrid/test_modeling_vit_hybrid.py
  tests/models/vit_mae/test_modeling_tf_vit_mae.py
  tests/models/vit_mae/test_modeling_vit_mae.py
  tests/models/vit_msn/test_modeling_vit_msn.py
  tests/models/yolos/test_modeling_yolos.py
  tests/test_modeling_common.py
  tests/test_modeling_flax_common.py
  utils/check_support_list.py
Labels: run-slow

#30775 Make `Gemma` work with `torch.compile`
  src/transformers/models/dbrx/modeling_dbrx.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/jetmoe/modeling_jetmoe.py
  src/transformers/models/phi3/modeling_phi3.py
  src/transformers/models/recurrent_gemma/modeling_recurrent_gemma.py
  tests/models/gemma/test_modeling_gemma.py
  tests/models/llama/test_modeling_llama.py
  tests/test_modeling_common.py
Labels: run-slow

#30835 TEST: Add llama logits tests
  tests/models/llama/test_modeling_llama.py
Labels: run-slow

#30865 [whisper] fix multilingual fine-tuning
  examples/pytorch/speech-recognition/run_speech_recognition_seq2seq.py
Labels: Audio

#30812 add return_token_timestamps to WhisperProcessor
  src/transformers/models/whisper/feature_extraction_whisper.py
  src/transformers/models/whisper/generation_whisper.py
  src/transformers/pipelines/automatic_speech_recognition.py
  tests/models/whisper/test_modeling_whisper.py
Labels: Good Second Issue, Audio

#30642 Add torch.compile for Mistral
  docs/source/en/llm_optims.md
  src/transformers/cache_utils.py
  src/transformers/generation/utils.py
  src/transformers/models/deprecated/open_llama/modeling_open_llama.py
  src/transformers/models/falcon/modeling_falcon.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/gpt_neox/modeling_gpt_neox.py
  src/transformers/models/gpt_neox_japanese/modeling_gpt_neox_japanese.py
  src/transformers/models/idefics/modeling_idefics.py
  src/transformers/models/llama/modeling_llama.py
  src/transformers/models/mistral/modeling_mistral.py
  src/transformers/models/mixtral/modeling_mixtral.py
  src/transformers/models/persimmon/modeling_persimmon.py
  src/transformers/models/phi/modeling_phi.py
  src/transformers/models/qwen2/modeling_qwen2.py
  src/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  src/transformers/models/stablelm/modeling_stablelm.py
  src/transformers/models/starcoder2/modeling_starcoder2.py
  tests/models/mistral/test_modeling_mistral.py
Labels: run-slow

#30851 Paligemma - fix slow tests, add bf16 and f16 slow tests
  tests/models/paligemma/test_modeling_paligemma.py
Labels: run-slow

#27836 [Whisper] Strip prompt before finding common subsequence
  src/transformers/models/whisper/tokenization_whisper.py
  tests/pipelines/test_pipelines_automatic_speech_recognition.py
Labels: Good Second Issue, Audio

#30967 Paligemma causal attention mask
  src/transformers/models/paligemma/modeling_paligemma.py
  src/transformers/models/paligemma/processing_paligemma.py
  tests/models/paligemma/test_modeling_paligemma.py
Labels: run-slow

#30989 Update 4 `MptIntegrationTests` expected outputs
  tests/models/mpt/test_modeling_mpt.py
Labels: run-slow

#29708 [Port] TensorFlow implementation of Mistral
  docs/source/en/index.md
  docs/source/en/model_doc/mistral.md
  src/transformers/__init__.py
  src/transformers/models/auto/modeling_tf_auto.py
  src/transformers/models/mistral/__init__.py
  src/transformers/models/mistral/modeling_tf_mistral.py
  src/transformers/utils/dummy_tf_objects.py
  tests/models/mistral/test_modeling_tf_mistral.py
Labels: TensorFlow, New model, single-model-run-slow, run-slow

#31082 Fix OWLv2 post_process_object_detection for multiple images
  src/transformers/models/owlv2/image_processing_owlv2.py
  tests/models/owlv2/test_image_processor_owlv2.py
Labels: run-slow

#30838 Add streaming, various fixes
  docs/source/en/agents.md
  src/transformers/agents/agents.py
  src/transformers/agents/llm_engine.py
  src/transformers/agents/prompts.py
  src/transformers/agents/python_interpreter.py
  src/transformers/agents/tools.py
  tests/agents/test_python_interpreter.py
Labels: Agents
