Repository huggingface/transformers, pull requests merged in 2024-06, with the labels that each got.

#30492 Add missing Flaubert tokenizer tests
  src/transformers/models/flaubert/tokenization_flaubert.py
  tests/models/flaubert/test_tokenization_flaubert.py
Labels: Core: Tokenization

#30536 Reduce by 2 the memory requirement in `generate()` 🔥🔥🔥
  src/transformers/cache_utils.py
  src/transformers/generation/candidate_generator.py
  src/transformers/generation/configuration_utils.py
  src/transformers/generation/utils.py
  src/transformers/models/cohere/modeling_cohere.py
  src/transformers/models/dbrx/modeling_dbrx.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/idefics2/modeling_idefics2.py
  src/transformers/models/llama/modeling_llama.py
  src/transformers/models/mistral/modeling_mistral.py
  src/transformers/models/mixtral/modeling_mixtral.py
  src/transformers/models/olmo/modeling_olmo.py
  src/transformers/models/persimmon/modeling_persimmon.py
  src/transformers/models/phi/modeling_phi.py
  src/transformers/models/phi3/modeling_phi3.py
  src/transformers/models/qwen2/modeling_qwen2.py
  src/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  src/transformers/models/stablelm/modeling_stablelm.py
  src/transformers/models/starcoder2/modeling_starcoder2.py
Labels: run-slow

#31269 Update text-to-speech.md
  docs/source/en/tasks/text-to-speech.md
Labels: Audio

#31188 Fixed Wav2Vec2ProcessorWithLM decoding error
  src/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py
Labels: Audio

#31207 Fix paligemma inverted mask
  src/transformers/models/paligemma/modeling_paligemma.py
  tests/models/paligemma/test_modeling_paligemma.py
Labels: run-slow

#31230 Fix gradio tool demos
  src/transformers/agents/agent_types.py
  src/transformers/agents/prompts.py
  src/transformers/agents/tools.py
Labels: Agents

#31197 add initial design for uniform processors + align model
  src/transformers/image_utils.py
  src/transformers/models/align/processing_align.py
  src/transformers/processing_utils.py
  src/transformers/tokenization_utils_base.py
  tests/models/align/test_processor_align.py
  tests/test_processing_common.py
Labels: run-slow

#31409 Agents: Improve python interpreter
  src/transformers/agents/default_tools.py
  src/transformers/agents/evaluate_agent.py
  src/transformers/agents/llm_engine.py
  src/transformers/agents/python_interpreter.py
  tests/agents/test_agents.py
  tests/agents/test_python_interpreter.py
Labels: Agents

#31480 Correct @is_flaky test decoration
  tests/models/gemma/test_modeling_gemma.py
  tests/test_modeling_common.py
Labels: run-slow

#27159 Add implementation of `spectrogram_batch`
  src/transformers/audio_utils.py
  tests/utils/test_audio_utils.py
Labels: Audio

#31031 [`GPT-NeoX`] Add SDPA support
  docs/source/en/model_doc/gpt_neox.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/gpt_neox/modeling_gpt_neox.py
  tests/models/gpt_neox/test_modeling_gpt_neox.py
Labels: run-slow

#31639 Fix RT-DETR inference with float16 and bfloat16
  src/transformers/models/rt_detr/modeling_rt_detr.py
  tests/models/rt_detr/test_modeling_rt_detr.py
Labels: run-slow

#31587 Fix paligemma detection inference
  src/transformers/models/paligemma/modeling_paligemma.py
  tests/models/paligemma/test_modeling_paligemma.py
Labels: run-slow

#31589 Fix dtype casting in swinv2 and swinv2sr to allow non-FP32 inference
  src/transformers/models/swin2sr/modeling_swin2sr.py
  src/transformers/models/swinv2/modeling_swinv2.py
  tests/models/swin2sr/test_modeling_swin2sr.py
  tests/models/swinv2/test_modeling_swinv2.py
Labels: run-slow
