Repository huggingface/transformers, pull requests merged in 2024-07, with the labels that each got.

#31401 fix assisted decoding
  src/transformers/generation/utils.py
  tests/generation/test_utils.py
Labels: Generation

#31671 Fix RT-DETR cache for generate_anchors
  src/transformers/models/rt_detr/modeling_rt_detr.py
  tests/models/rt_detr/test_modeling_rt_detr.py
Labels: run-slow

#31794 Fix gemma tests
  tests/models/gemma/test_modeling_gemma.py
Labels: run-slow

#31769 Code agent: allow function persistence between steps
  src/transformers/agents/agent_types.py
  src/transformers/agents/agents.py
  src/transformers/agents/python_interpreter.py
  tests/agents/test_agents.py
  tests/agents/test_python_interpreter.py
Labels: Agents

#31495 Add training support for SigLIP
  docs/source/en/model_doc/siglip.md
  src/transformers/models/siglip/modeling_siglip.py
  tests/models/siglip/test_modeling_siglip.py
Labels: run-slow

#31714 Fix Wav2Vec2 Fairseq conversion (weight norm state dict keys)
  src/transformers/models/wav2vec2/convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py
Labels: Audio

#31499 Add FA2 and `sdpa` support for SigLIP
  docs/source/en/model_doc/siglip.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/idefics2/modeling_idefics2.py
  src/transformers/models/siglip/modeling_siglip.py
  tests/models/siglip/test_modeling_siglip.py
Labels: run-slow

#31446 Refactor flash attention implementation in transformers
  src/transformers/__init__.py
  src/transformers/modeling_flash_attention_utils.py
  src/transformers/models/bark/modeling_bark.py
  src/transformers/models/bart/modeling_bart.py
  src/transformers/models/cohere/modeling_cohere.py
  src/transformers/models/data2vec/modeling_data2vec_audio.py
  src/transformers/models/dbrx/modeling_dbrx.py
  src/transformers/models/distilbert/modeling_distilbert.py
  src/transformers/models/falcon/modeling_falcon.py
  src/transformers/models/gemma/diff_gemma.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/gemma2/diff_gemma2.py
  src/transformers/models/gemma2/modeling_gemma2.py
  src/transformers/models/gpt2/modeling_gpt2.py
  src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
  src/transformers/models/gpt_neo/modeling_gpt_neo.py
  src/transformers/models/gpt_neox/modeling_gpt_neox.py
  src/transformers/models/gptj/modeling_gptj.py
  src/transformers/models/hubert/modeling_hubert.py
  src/transformers/models/idefics2/modeling_idefics2.py
  src/transformers/models/jamba/modeling_jamba.py
  src/transformers/models/jetmoe/modeling_jetmoe.py
  src/transformers/models/llama/modeling_llama.py
  src/transformers/models/llava_next_video/diff_llava_next_video.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/m2m_100/modeling_m2m_100.py
  src/transformers/models/mbart/modeling_mbart.py
  src/transformers/models/mistral/modeling_mistral.py
  src/transformers/models/mixtral/modeling_mixtral.py
  src/transformers/models/musicgen/modeling_musicgen.py
  src/transformers/models/musicgen_melody/modeling_musicgen_melody.py
  src/transformers/models/olmo/modeling_olmo.py
  src/transformers/models/opt/modeling_opt.py
  src/transformers/models/phi/modeling_phi.py
  src/transformers/models/phi3/modeling_phi3.py
  src/transformers/models/qwen2/configuration_qwen2.py
  src/transformers/models/qwen2/modeling_qwen2.py
  src/transformers/models/qwen2_moe/configuration_qwen2_moe.py
  src/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  src/transformers/models/sew/modeling_sew.py
  src/transformers/models/siglip/modeling_siglip.py
  src/transformers/models/stablelm/modeling_stablelm.py
  src/transformers/models/starcoder2/modeling_starcoder2.py
  src/transformers/models/unispeech/modeling_unispeech.py
  src/transformers/models/unispeech_sat/modeling_unispeech_sat.py
  src/transformers/models/wav2vec2/modeling_wav2vec2.py
  src/transformers/models/whisper/modeling_whisper.py
  src/transformers/utils/import_utils.py
  utils/check_config_attributes.py
Labels: run-slow

#30952 🚨 fix(SigLip): remove spurious exclusion of first vision output token
  src/transformers/models/siglip/modeling_siglip.py
Labels: run-slow

#30356 Adding hiera
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/hiera.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/hiera/__init__.py
  src/transformers/models/hiera/configuration_hiera.py
  src/transformers/models/hiera/convert_hiera_to_hf.py
  src/transformers/models/hiera/modeling_hiera.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/fx.py
  tests/models/hiera/__init__.py
  tests/models/hiera/test_modeling_hiera.py
  tests/test_modeling_common.py
  utils/check_repo.py
Labels: run-slow

#27818 fix prompt strip to support tensors and np arrays
  src/transformers/models/whisper/tokenization_whisper.py
  src/transformers/models/whisper/tokenization_whisper_fast.py
  tests/models/whisper/test_tokenization_whisper.py
Labels: Audio

#31771 Speedup model init on CPU (by 10x+ for llama-3-8B as one example)
  docs/source/en/main_classes/model.md
  src/transformers/modeling_utils.py
  src/transformers/models/encoder_decoder/modeling_encoder_decoder.py
  src/transformers/models/lxmert/modeling_lxmert.py
  src/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py
  tests/models/bart/test_modeling_bart.py
  tests/models/bigbird_pegasus/test_modeling_bigbird_pegasus.py
  tests/models/longt5/test_modeling_longt5.py
  tests/models/lxmert/test_modeling_lxmert.py
  tests/models/m2m_100/test_modeling_m2m_100.py
  tests/models/mbart/test_modeling_mbart.py
  tests/models/nllb_moe/test_modeling_nllb_moe.py
  tests/models/plbart/test_modeling_plbart.py
  tests/models/seamless_m4t/test_modeling_seamless_m4t.py
  tests/models/seamless_m4t_v2/test_modeling_seamless_m4t_v2.py
  tests/models/switch_transformers/test_modeling_switch_transformers.py
  tests/utils/test_modeling_utils.py
Labels: run-slow

#31534 Chameleon: add model
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/chameleon.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/chameleon/__init__.py
  src/transformers/models/chameleon/configuration_chameleon.py
  src/transformers/models/chameleon/convert_chameleon_weights_to_hf.py
  src/transformers/models/chameleon/image_processing_chameleon.py
  src/transformers/models/chameleon/modeling_chameleon.py
  src/transformers/models/chameleon/processing_chameleon.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/models/chameleon/__init__.py
  tests/models/chameleon/test_image_processing_chameleon.py
  tests/models/chameleon/test_modeling_chameleon.py
  tests/test_modeling_common.py
  utils/check_repo.py
Labels: run-slow

#32012 Fix tests skip
  tests/models/big_bird/test_modeling_big_bird.py
  tests/models/whisper/test_modeling_whisper.py
  tests/test_tokenization_common.py
Labels: run-slow

#31572 Add language to word timestamps for Whisper
  src/transformers/models/whisper/tokenization_whisper.py
  tests/pipelines/test_pipelines_automatic_speech_recognition.py
Labels: Audio

#31940 Add `sdpa` and FA2 for CLIP
  docs/source/en/model_doc/clip.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/altclip/modeling_altclip.py
  src/transformers/models/clip/modeling_clip.py
  src/transformers/models/clipseg/modeling_clipseg.py
  src/transformers/models/git/modeling_git.py
  src/transformers/models/groupvit/modeling_groupvit.py
  src/transformers/models/idefics/vision.py
  src/transformers/models/kosmos2/modeling_kosmos2.py
  src/transformers/models/owlv2/modeling_owlv2.py
  src/transformers/models/owlvit/modeling_owlvit.py
  src/transformers/models/siglip/modeling_siglip.py
  src/transformers/models/x_clip/modeling_x_clip.py
  tests/models/clip/test_modeling_clip.py
Labels: Vision, run-slow

#32050 [mistral] Support passing `head_dim` through config (and do not require `head_dim * num_heads == hidden_size`)
  src/transformers/models/mistral/configuration_mistral.py
  src/transformers/models/mistral/modeling_mistral.py
Labels: run-slow

#31247 Add torch.compile Support For Mamba
  src/transformers/cache_utils.py
  src/transformers/generation/utils.py
  src/transformers/models/mamba/modeling_mamba.py
  tests/models/mamba/test_modeling_mamba.py
Labels: run-slow

#32003 Incorrect Whisper long-form decoding timestamps
  src/transformers/models/clvp/processing_clvp.py
  src/transformers/models/whisper/processing_whisper.py
  src/transformers/models/whisper/tokenization_whisper.py
  src/transformers/models/whisper/tokenization_whisper_fast.py
  tests/models/whisper/test_modeling_whisper.py
Labels: Audio

#30984 Support generating with fallback for short form audio in Whisper
  src/transformers/models/whisper/generation_whisper.py
  tests/models/whisper/test_modeling_whisper.py
Labels: Audio

#31702 Agents planning
  src/transformers/agents/agents.py
  src/transformers/agents/default_tools.py
  src/transformers/agents/prompts.py
  src/transformers/agents/python_interpreter.py
  tests/agents/test_agents.py
  tests/agents/test_python_interpreter.py
Labels: Agents

#31857 feat(cache): StaticCache uses index_copy_ to avoid useless copy
  src/transformers/cache_utils.py
Labels: run-slow

#31783 Support dequantizing GGUF FP16 format
  src/transformers/integrations/ggml.py
  tests/quantization/ggml/test_ggml.py
Labels: Quantization

#32241 Flash-Attn: fix generation when no attention mask or no pading
  src/transformers/modeling_flash_attention_utils.py
  tests/test_modeling_common.py
Labels: run-slow

#31445 🚨 Bloom support for cache class
  src/transformers/generation/candidate_generator.py
  src/transformers/generation/utils.py
  src/transformers/models/bloom/modeling_bloom.py
  src/transformers/models/musicgen_melody/modeling_musicgen_melody.py
  src/transformers/models/persimmon/modeling_persimmon.py
  tests/generation/test_utils.py
Labels: run-slow

#32276 fixes to properly shard FSDP across cpu and meta for cpu_efficient_loading for prequantized 4bit
  src/transformers/modeling_utils.py
  src/transformers/quantizers/quantizer_bnb_4bit.py
Labels: PyTorch FSDP

#32275 [Idefics2] - Fix FA2 call for Perceiver layer
  src/transformers/models/idefics2/modeling_idefics2.py
  tests/models/idefics2/test_modeling_idefics2.py
Labels: run-slow
