Repository huggingface/transformers, pull requests merged in 2024-10, with the labels that each got.

#33824 Workaround for bark issue in pipelines
  src/transformers/models/bark/modeling_bark.py
Labels: run-slow

#33851 Fix device mismatch errors
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava_next/modeling_llava_next.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/llava_next_video/modular_llava_next_video.py
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/vipllava/modeling_vipllava.py
Labels: run-slow

#33339 Move weight initilization deformabledetr
  src/transformers/models/deformable_detr/modeling_deformable_detr.py
  src/transformers/models/grounding_dino/modeling_grounding_dino.py
  src/transformers/models/rt_detr/modeling_rt_detr.py
Labels: Core: Modeling, Vision, run-slow

#33873 Repo consistency fix after #33339
  src/transformers/models/omdet_turbo/modeling_omdet_turbo.py
Labels: run-slow

#31368 Uniformize model processors
  src/transformers/models/blip/processing_blip.py
  src/transformers/models/blip_2/processing_blip_2.py
  src/transformers/models/bridgetower/processing_bridgetower.py
  src/transformers/models/donut/processing_donut.py
  src/transformers/models/idefics3/processing_idefics3.py
  src/transformers/models/mllama/processing_mllama.py
  src/transformers/models/omdet_turbo/processing_omdet_turbo.py
  src/transformers/models/wav2vec2/processing_wav2vec2.py
  src/transformers/models/wav2vec2_bert/processing_wav2vec2_bert.py
  src/transformers/processing_utils.py
  tests/models/altclip/test_processor_altclip.py
  tests/models/blip/test_processor_blip.py
  tests/models/blip_2/test_processor_blip_2.py
  tests/models/bridgetower/test_processing_bridgetower.py
  tests/models/donut/test_processing_donut.py
  tests/models/wav2vec2/test_processor_wav2vec2.py
  tests/models/wav2vec2_bert/test_processor_wav2vec2_bert.py
  tests/test_processing_common.py
Labels: run-slow

#33724 Add sdpa for DistilBert
  docs/source/en/model_doc/distilbert.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/distilbert/modeling_distilbert.py
Labels: run-slow

#33600 Optim deformable detr
  src/transformers/models/deformable_detr/modeling_deformable_detr.py
  src/transformers/models/grounding_dino/modeling_grounding_dino.py
  src/transformers/models/mask2former/modeling_mask2former.py
  src/transformers/models/oneformer/modeling_oneformer.py
  src/transformers/models/rt_detr/modeling_rt_detr.py
Labels: run-slow

#32652 Add `SplinterTokenizer` unit test
  src/transformers/models/splinter/tokenization_splinter.py
  tests/models/splinter/test_tokenization_splinter.py
Labels: Core: Tokenization

#33665 [Tests] Diverse Whisper fixes
  src/transformers/models/qwen2_audio/modeling_qwen2_audio.py
  src/transformers/models/whisper/generation_whisper.py
  src/transformers/models/whisper/modeling_whisper.py
  tests/models/whisper/test_modeling_whisper.py
Labels: run-slow

#33920 Fix distil whisper segment computation
  src/transformers/models/whisper/generation_whisper.py
  tests/models/whisper/test_modeling_whisper.py
Labels: run-slow

#32613 Fix attn mask ignore logic in training-time trace
  src/transformers/cache_utils.py
  src/transformers/modeling_attn_mask_utils.py
  tests/models/gemma/test_modeling_gemma.py
  tests/models/llama/test_modeling_llama.py
  tests/models/mistral/test_modeling_mistral.py
  tests/models/nemotron/test_modeling_nemotron.py
  tests/test_modeling_common.py
Labels: run-slow

#30950 Add Zamba
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/zamba.md
  src/transformers/__init__.py
  src/transformers/generation/utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/zamba/__init__.py
  src/transformers/models/zamba/configuration_zamba.py
  src/transformers/models/zamba/modeling_zamba.py
  src/transformers/utils/dummy_pt_objects.py
  tests/generation/test_utils.py
  tests/models/zamba/__init__.py
  tests/models/zamba/test_modeling_zamba.py
  utils/check_config_attributes.py
  utils/not_doctested.txt
Labels: New model, run-slow

#33903 [`TF`] Fix Tensorflow XLA Generation on limited seq_len models
  tests/test_modeling_tf_common.py
Labels: run-slow

#32049 Enable customized optimizer for DeepSpeed
  src/transformers/trainer.py
Labels: trainer, DeepSpeed, optimization

#33859 Add support for __all__ and potentilly deleting functions
  docs/source/en/modular_transformers.md
  examples/modular-transformers/modeling_dummy.py
  src/transformers/__init__.py
  src/transformers/deepspeed.py
  src/transformers/models/gemma/configuration_gemma.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/gemma/modular_gemma.py
  src/transformers/models/gemma/tokenization_gemma.py
  src/transformers/models/instructblipvideo/modeling_instructblipvideo.py
  src/transformers/models/llama/tokenization_llama.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/seamless_m4t/modeling_seamless_m4t.py
  src/transformers/models/seamless_m4t_v2/modeling_seamless_m4t_v2.py
  utils/modular_model_converter.py
  utils/not_doctested.txt
Labels: run-benchmark

#33918 BatchFeature.to() supports non-tensor keys
  src/transformers/feature_extraction_utils.py
  src/transformers/models/pixtral/image_processing_pixtral.py
  src/transformers/models/pixtral/processing_pixtral.py
  src/transformers/tokenization_utils_base.py
Labels: run-slow

#34007 Fixup DeepSpeed things
  src/transformers/trainer.py
Labels: DeepSpeed

#33298 add sdpa to OPT
  docs/source/en/model_doc/opt.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/opt/modeling_opt.py
  tests/models/opt/test_modeling_flax_opt.py
  tests/models/opt/test_modeling_opt.py
  tests/models/opt/test_modeling_tf_opt.py
Labels: run-slow

#33383 Universal Assisted Generation: Assisted generation with any assistant model (by Intel Labs)
  docs/source/en/generation_strategies.md
  src/transformers/generation/candidate_generator.py
  src/transformers/generation/utils.py
  tests/generation/test_utils.py
Labels: run-slow

#33707 Generate using exported model and enable gemma2-2b in ExecuTorch
  src/transformers/integrations/executorch.py
  tests/models/gemma/test_modeling_gemma.py
  tests/models/gemma2/test_modeling_gemma2.py
Labels: run-slow

#34071 avoid many failures for ImageGPT
  tests/models/imagegpt/test_modeling_imagegpt.py
  tests/models/video_llava/test_modeling_video_llava.py
Labels: run-slow

#34070 Avoid many test failures for `LlavaNextVideoForConditionalGeneration`
  tests/generation/test_utils.py
Labels: run-slow

#33757 Add sdpa for Vivit
  docs/source/en/model_doc/vivit.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/vivit/modeling_vivit.py
  tests/models/vivit/test_modeling_vivit.py
Labels: Vision, SDPA, run-slow

#33624 Moshi integration
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/mimi.md
  docs/source/en/model_doc/moshi.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/convert_slow_tokenizer.py
  src/transformers/generation/utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/feature_extraction_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/moshi/__init__.py
  src/transformers/models/moshi/configuration_moshi.py
  src/transformers/models/moshi/convert_moshi_transformers.py
  src/transformers/models/moshi/modeling_moshi.py
  src/transformers/utils/dummy_pt_objects.py
  tests/generation/test_utils.py
  tests/models/mimi/test_modeling_mimi.py
  tests/models/moshi/__init__.py
  tests/models/moshi/test_modeling_moshi.py
  tests/models/moshi/test_tokenization_moshi.py
  utils/check_repo.py
Labels: run-slow

#34023 fix(Wav2Vec2ForCTC): torch export
  src/transformers/models/hubert/modeling_hubert.py
  src/transformers/models/unispeech/modeling_unispeech.py
  src/transformers/models/unispeech_sat/modeling_unispeech_sat.py
  src/transformers/models/wav2vec2/modeling_wav2vec2.py
Labels: run-slow

#33823 add Glm
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/glm.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/glm/__init__.py
  src/transformers/models/glm/configuration_glm.py
  src/transformers/models/glm/convert_glm_weights_to_hf.py
  src/transformers/models/glm/modeling_glm.py
  src/transformers/models/glm/modular_glm.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/import_utils.py
  tests/models/glm/__init__.py
  tests/models/glm/test_modeling_glm.py
  tests/test_modeling_common.py
Labels: run-slow

#34208 Support boolean tool args
  src/transformers/agents/tools.py
Labels: Agents

#34414 Fix bnb training test failure
  tests/quantization/bnb/test_4bit.py
  tests/quantization/bnb/test_mixed_int8.py
Labels: Tests

#31817 New option called `"best"` for `args.save_strategy`.
  src/transformers/trainer.py
  src/transformers/trainer_callback.py
  src/transformers/trainer_utils.py
  src/transformers/training_args.py
  src/transformers/training_args_tf.py
  tests/trainer/test_trainer.py
Labels: trainer

#33200 🚨🚨🚨 [SuperPoint] Fix keypoint coordinate output and add post processing
  docs/source/en/model_doc/superpoint.md
  src/transformers/models/superpoint/image_processing_superpoint.py
  src/transformers/models/superpoint/modeling_superpoint.py
  tests/models/superpoint/test_image_processing_superpoint.py
  tests/models/superpoint/test_modeling_superpoint.py
Labels: bug, Vision

#34476 Albert is ExecuTorch compatible
  tests/models/albert/test_modeling_albert.py
Labels: run-slow, ExecuTorch

#34425 Roberta is ExecuTorch compatible
  tests/models/roberta/test_modeling_roberta.py
Labels: run-slow, ExecuTorch

#34486 fix pixtral processor
  src/transformers/models/pixtral/configuration_pixtral.py
  src/transformers/models/pixtral/modeling_pixtral.py
  src/transformers/models/pixtral/processing_pixtral.py
  tests/models/pixtral/test_modeling_pixtral.py
  tests/models/pixtral/test_processor_pixtral.py
Labels: run-slow

#34226 UPDATE Documentation for #TRANSLATING.md Documentation into Multiple Languages.(Changes made)
  docs/TRANSLATING.md
Labels: Documentation

#34536 feat: add benchmarks pg indexes
  .github/workflows/benchmark.yml
  benchmark/init_db.sql
Labels: run-benchmark
