Repository huggingface/transformers, pull requests merged in 2024-09, with the labels that each got.

#33177 Add GraniteRMSNorm
  src/transformers/models/granite/modeling_granite.py
  src/transformers/pytorch_utils.py
Labels: run-slow

#33122 remove to restriction for 4-bit model
  src/transformers/modeling_utils.py
  tests/quantization/bnb/test_4bit.py
Labels: Quantization

#32625 🚨 Support dequantization for most GGML types
  docs/source/en/gguf.md
  src/transformers/integrations/ggml.py
  src/transformers/modeling_gguf_pytorch_utils.py
  src/transformers/testing_utils.py
  src/transformers/utils/__init__.py
  src/transformers/utils/import_utils.py
  tests/quantization/ggml/test_ggml.py
Labels: Quantization

#32092 Add sdpa support for Albert
  docs/source/en/model_doc/albert.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/albert/modeling_albert.py
Labels: run-slow

#31731 Only disallow DeepSpeed Zero-3 for auto bs finder
  src/transformers/trainer.py
  tests/trainer/test_trainer.py
Labels: DeepSpeed

#33265 Add new documentation page for advanced agent usage
  docs/source/en/_toctree.yml
  docs/source/en/agents.md
  docs/source/en/agents_advanced.md
Labels: Agents

#33154 Fix excessive CPU memory usage with FSDP and cpu_ram_efficient_loading
  src/transformers/modeling_utils.py
Labels: PyTorch FSDP

#32673 Llava Onevision: add model
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/llava_onevision.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/cache_utils.py
  src/transformers/generation/utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/llava_onevision/__init__.py
  src/transformers/models/llava_onevision/configuration_llava_onevision.py
  src/transformers/models/llava_onevision/convert_llava_onevision_weights_to_hf.py
  src/transformers/models/llava_onevision/image_processing_llava_onevision.py
  src/transformers/models/llava_onevision/modeling_llava_onevision.py
  src/transformers/models/llava_onevision/processing_llava_onevision.py
  src/transformers/models/llava_onevision/video_processing_llava_onevision.py
  src/transformers/processing_utils.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/generation/test_utils.py
  tests/models/llava_onevision/__init__.py
  tests/models/llava_onevision/test_image_processing_llava_onevision.py
  tests/models/llava_onevision/test_modeling_llava_onevision.py
  tests/models/llava_onevision/test_processing_llava_onevision.py
  tests/test_modeling_common.py
Labels: run-slow

#33161 simple align qwen2vl kv_seq_len calculation with qwen2
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
  tests/models/qwen2_vl/test_modeling_qwen2_vl.py
Labels: run-slow

#33162 Load dynamic module (remote code) only once if code isn't change
  src/transformers/dynamic_module_utils.py
  tests/models/auto/test_configuration_auto.py
  tests/models/auto/test_feature_extraction_auto.py
  tests/models/auto/test_image_processing_auto.py
  tests/models/auto/test_modeling_auto.py
  tests/models/auto/test_tokenization_auto.py
Labels: run-slow

#32033 add sdpa mbart
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/mbart/modeling_mbart.py
Labels: run-slow

#33353 Add visit webpage tool
  docs/source/en/main_classes/agent.md
  src/transformers/__init__.py
  src/transformers/agents/__init__.py
  src/transformers/agents/search.py
Labels: Agents

#32907 VLM: fixes after refactor
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava/processing_llava.py
  src/transformers/models/llava_next/modeling_llava_next.py
  src/transformers/models/llava_next/processing_llava_next.py
  src/transformers/models/llava_next_video/diff_llava_next_video.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/llava_next_video/processing_llava_next_video.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/video_llava/processing_video_llava.py
  src/transformers/models/vipllava/modeling_vipllava.py
  tests/models/llava/test_modeling_llava.py
  tests/models/llava_next/test_modeling_llava_next.py
  tests/models/llava_next_video/test_modeling_llava_next_video.py
  tests/models/video_llava/test_modeling_video_llava.py
  tests/models/vipllava/test_modeling_vipllava.py
Labels: run-slow

#33364 fixed Mask2Former image processor segmentation maps handling
  src/transformers/models/mask2former/image_processing_mask2former.py
  tests/models/mask2former/test_image_processing_mask2former.py
Labels: Vision

#31844 Add support for GGUF Phi-3
  docs/source/en/gguf.md
  src/transformers/convert_slow_tokenizer.py
  src/transformers/convert_slow_tokenizers_checkpoints_to_fast.py
  src/transformers/integrations/ggml.py
  tests/quantization/ggml/test_ggml.py
Labels: GGUF

#33258 Dynamic number of speculative tokens in order to accelerate speculative decoding
  src/transformers/generation/__init__.py
  src/transformers/generation/candidate_generator.py
  src/transformers/generation/configuration_utils.py
  src/transformers/generation/stopping_criteria.py
  src/transformers/generation/utils.py
  tests/generation/test_stopping_criteria.py
Labels: Generation

#33449 Add support for Pixtral
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/pixtral.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/llava/configuration_llava.py
  src/transformers/models/pixtral/__init__.py
  src/transformers/models/pixtral/configuration_pixtral.py
  src/transformers/models/pixtral/convert_pixtral_weights_to_hf.py
  src/transformers/models/pixtral/image_processing_pixtral.py
  src/transformers/models/pixtral/modeling_pixtral.py
  src/transformers/models/pixtral/processing_pixtral.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/models/llava/test_modeling_llava.py
  tests/models/pixtral/__init__.py
  tests/models/pixtral/test_image_processing_pixtral.py
  tests/models/pixtral/test_modeling_pixtral.py
  tests/models/pixtral/test_processor_pixtral.py
Labels: New model

#33450 [Whisper test] Fix some failing tests
  tests/models/whisper/test_modeling_whisper.py
Labels: run-slow

#33499 fix patch_attention_mask incorrect setting which leads to the differe…
  src/transformers/models/idefics2/modeling_idefics2.py
  tests/models/idefics2/test_modeling_idefics2.py
Labels: run-slow

#33439 Decorator for easier tool building
  docs/source/en/agents.md
  docs/source/en/agents_advanced.md
  docs/source/en/main_classes/agent.md
  src/transformers/__init__.py
  src/transformers/agents/__init__.py
  src/transformers/agents/agent_types.py
  src/transformers/agents/agents.py
  src/transformers/agents/default_tools.py
  src/transformers/agents/document_question_answering.py
  src/transformers/agents/image_question_answering.py
  src/transformers/agents/prompts.py
  src/transformers/agents/search.py
  src/transformers/agents/speech_to_text.py
  src/transformers/agents/text_to_speech.py
  src/transformers/agents/tools.py
  src/transformers/agents/translation.py
  src/transformers/utils/chat_template_utils.py
  tests/agents/test_agents.py
  tests/agents/test_final_answer.py
  tests/agents/test_python_interpreter.py
  tests/agents/test_tools_common.py
Labels: Agents

#33560 fix tests with main revision and read token
  tests/models/mamba2/test_modeling_mamba2.py
Labels: run-slow

#31198 add uniform processors for altclip + chinese_clip
  src/transformers/models/align/processing_align.py
  src/transformers/models/altclip/processing_altclip.py
  src/transformers/models/chinese_clip/image_processing_chinese_clip.py
  src/transformers/models/chinese_clip/processing_chinese_clip.py
  src/transformers/processing_utils.py
  tests/models/altclip/test_processor_altclip.py
  tests/models/chinese_clip/test_processor_chinese_clip.py
  tests/models/instructblip/test_processor_instructblip.py
  tests/models/instructblipvideo/test_processor_instructblipvideo.py
  tests/test_processing_common.py
Labels: run-slow

#33520 [`Mamba2`] Move dt calculations to kernel
  src/transformers/models/mamba2/modeling_mamba2.py
  tests/models/mamba2/test_modeling_mamba2.py
Labels: run-slow

#32599 Update modeling_mamba2.py, fix pad size
  src/transformers/models/mamba2/modeling_mamba2.py
  tests/models/mamba2/test_modeling_mamba2.py
Labels: run-slow

#33592 Add sdpa for BioGpt
  docs/source/en/model_doc/biogpt.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/biogpt/modeling_biogpt.py
Labels: run-slow

#33507 Fix contrastive search to correctly handle input with padding
  src/transformers/generation/utils.py
  tests/generation/test_utils.py
Labels: Generation

#33312 Fix qwen2vl float16 inference bug
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
Labels: float16

#33403 Sdpa dino v2
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/dinov2/modeling_dinov2.py
  tests/models/dinov2/test_modeling_dinov2.py
Labels: run-slow

#33309 Add SDPA support for M2M100
  docs/source/en/model_doc/m2m_100.md
  docs/source/en/model_doc/nllb.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/models/m2m_100/modeling_m2m_100.py
Labels: run-slow

#31843 Add OmDet-Turbo
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/omdet-turbo.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/omdet_turbo/__init__.py
  src/transformers/models/omdet_turbo/configuration_omdet_turbo.py
  src/transformers/models/omdet_turbo/convert_omdet_turbo_to_hf.py
  src/transformers/models/omdet_turbo/modeling_omdet_turbo.py
  src/transformers/models/omdet_turbo/processing_omdet_turbo.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/omdet_turbo/__init__.py
  tests/models/omdet_turbo/test_modeling_omdet_turbo.py
  tests/models/omdet_turbo/test_processor_omdet_turbo.py
  utils/check_table.py
Labels: run-slow

#32600 adding positional encoder changes and tests
  src/transformers/models/altclip/modeling_altclip.py
  src/transformers/models/bridgetower/modeling_bridgetower.py
  src/transformers/models/chinese_clip/modeling_chinese_clip.py
  src/transformers/models/clip/modeling_clip.py
  src/transformers/models/clipseg/modeling_clipseg.py
  src/transformers/models/git/modeling_git.py
  src/transformers/models/kosmos2/modeling_kosmos2.py
  src/transformers/models/x_clip/modeling_x_clip.py
  tests/models/altclip/test_modeling_altclip.py
  tests/models/bridgetower/test_modeling_bridgetower.py
  tests/models/chinese_clip/test_modeling_chinese_clip.py
  tests/models/clip/test_modeling_clip.py
  tests/models/clipseg/test_modeling_clipseg.py
  tests/models/git/test_modeling_git.py
  tests/models/kosmos2/test_modeling_kosmos2.py
  tests/models/x_clip/test_modeling_x_clip.py
Labels: run-slow

#33678 Fix position embeddings singular/plural
  src/transformers/models/blip/modeling_blip.py
  src/transformers/models/blip_2/modeling_blip_2.py
  src/transformers/models/instructblip/modeling_instructblip.py
  src/transformers/models/instructblip/processing_instructblip.py
  src/transformers/models/instructblipvideo/modeling_instructblipvideo.py
Labels: run-slow

#33330 Fix ViT-MAE decoder interpolate
  src/transformers/models/vit_mae/modeling_vit_mae.py
  tests/models/vit_mae/test_modeling_vit_mae.py
Labels: run-slow
