Repository huggingface/transformers, pull requests merged in 2025-08, with the labels that each got.

#39881 Better return type hint for `AutoModelForCausalLM` and `AutoModelForImageTextToText`
  src/transformers/models/auto/modeling_auto.py
Labels: typing

#39824 [DOCS] : Improved mimi model card
  docs/source/en/model_doc/mimi.md
Labels: Audio

#39915 Fix broken image inference for Fuyu model
  src/transformers/models/fuyu/modeling_fuyu.py
  tests/models/fuyu/test_modeling_fuyu.py
Labels: for patch

#39742 Update HuBERT model card according to template
  docs/source/en/model_doc/hubert.md
Labels: Audio

#39993 Default to dequantize if cpu in device_map for mxfp4
  src/transformers/quantizers/quantizer_mxfp4.py
Labels: for patch

#40007 🚨 Use lru_cache for sine pos embeddings MaskFormer
  src/transformers/models/mask2former/modeling_mask2former.py
  src/transformers/models/maskformer/modeling_maskformer.py
  src/transformers/models/oneformer/modeling_oneformer.py
Labels: run-slow

#40261 Fix slow static cache export tests
  src/transformers/integrations/executorch.py
  tests/models/gemma/test_modeling_gemma.py
  tests/models/gemma2/test_modeling_gemma2.py
  tests/models/llama/test_modeling_llama.py
  tests/models/olmo/test_modeling_olmo.py
  tests/models/phi3/test_modeling_phi3.py
  tests/models/qwen2/test_modeling_qwen2.py
  tests/models/qwen3/test_modeling_qwen3.py
Labels: run-slow

#38188 Add support for Florence-2
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/florence2.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/florence2/__init__.py
  src/transformers/models/florence2/configuration_florence2.py
  src/transformers/models/florence2/convert_florence2_original_pytorch_to_hf.py
  src/transformers/models/florence2/modeling_florence2.py
  src/transformers/models/florence2/modular_florence2.py
  src/transformers/models/florence2/processing_florence2.py
  tests/models/florence2/__init__.py
  tests/models/florence2/test_modeling_florence2.py
  tests/models/florence2/test_processing_florence2.py
  utils/check_repo.py
Labels: New model

#39944 Add back `_tp_plan` attribute
  conftest.py
  src/transformers/configuration_utils.py
  src/transformers/integrations/tensor_parallel.py
  src/transformers/modeling_utils.py
  tests/tensor_parallel/test_tensor_parallel.py
Labels: Core: Modeling, Tensor Parallel

#39606 HunYuan opensource
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/hunyuan_v1_dense.md
  docs/source/en/model_doc/hunyuan_v1_moe.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/hunyuan_v1_dense/__init__.py
  src/transformers/models/hunyuan_v1_dense/configuration_hunyuan_v1_dense.py
  src/transformers/models/hunyuan_v1_dense/modeling_hunyuan_v1_dense.py
  src/transformers/models/hunyuan_v1_dense/modular_hunyuan_v1_dense.py
  src/transformers/models/hunyuan_v1_moe/__init__.py
  src/transformers/models/hunyuan_v1_moe/configuration_hunyuan_v1_moe.py
  src/transformers/models/hunyuan_v1_moe/modeling_hunyuan_v1_moe.py
  src/transformers/models/hunyuan_v1_moe/modular_hunyuan_v1_moe.py
  tests/models/hunyuan_v1_dense/__init__.py
  tests/models/hunyuan_v1_dense/test_modeling_hunyuan_v1_dense.py
  tests/models/hunyuan_v1_moe/__init__.py
  tests/models/hunyuan_v1_moe/test_modeling_hunyuan_v1_moe.py
Labels: New model

#40341 wav2vec2 fixes
  tests/models/wav2vec2/test_modeling_wav2vec2.py
Labels: Audio

#40272 Addiing ByteDance Seed Seed-OSS
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/seed_oss.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/seed_oss/__init__.py
  src/transformers/models/seed_oss/configuration_seed_oss.py
  src/transformers/models/seed_oss/modeling_seed_oss.py
  src/transformers/models/seed_oss/modular_seed_oss.py
  tests/models/seed_oss/__init__.py
  tests/models/seed_oss/test_modeling_seed_oss.py
  tests/repo_utils/modular/test_conversion_order.py
Labels: New model
