Repository huggingface/transformers, pull requests merged in 2025-03, with the labels that each got.

#36455 Fix loading zero3 weights
  src/transformers/integrations/deepspeed.py
  src/transformers/modeling_utils.py
  tests/deepspeed/test_deepspeed.py
Labels: bug

#36521 Add aya
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/aya_vision.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/aya_vision/__init__.py
  src/transformers/models/aya_vision/configuration_aya_vision.py
  src/transformers/models/aya_vision/modeling_aya_vision.py
  src/transformers/models/aya_vision/processing_aya_vision.py
  src/transformers/utils/dummy_pt_objects.py
  tests/generation/test_utils.py
  tests/models/aya_vision/__init__.py
  tests/models/aya_vision/test_modeling_aya_vision.py
  tests/models/aya_vision/test_processor_aya_vision.py
Labels: New model

#36313 Add support for fast image processors in add-new-model-like CLI
  docs/source/en/add_new_model.md
  src/transformers/commands/add_fast_image_processor.py
  src/transformers/commands/add_new_model_like.py
Labels: Core: CLI

#36422 🚨🚨🚨 Fix sdpa in sam and refactor relative position embeddings
  src/transformers/models/got_ocr2/modeling_got_ocr2.py
  src/transformers/models/sam/image_processing_sam.py
  src/transformers/models/sam/modeling_sam.py
  src/transformers/models/sam/modeling_tf_sam.py
  src/transformers/processing_utils.py
  tests/models/sam/test_processor_sam.py
Labels: Vision

#36790 Add Mistral3
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/mistral3.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/mistral3/__init__.py
  src/transformers/models/mistral3/configuration_mistral3.py
  src/transformers/models/mistral3/convert_mistral3_weights_to_hf.py
  src/transformers/models/mistral3/modeling_mistral3.py
  src/transformers/models/mistral3/modular_mistral3.py
  src/transformers/models/pixtral/image_processing_pixtral.py
  src/transformers/models/pixtral/processing_pixtral.py
  src/transformers/utils/dummy_pt_objects.py
  tests/generation/test_utils.py
  tests/models/mistral3/__init__.py
  tests/models/mistral3/test_modeling_mistral3.py
  tests/models/mistral3/test_processor_mistral3.py
  tests/models/pixtral/test_image_processing_pixtral.py
Labels: New model

#36741 [gemma 3] multimodal checkpoints + AutoModelForCausalLM
  src/transformers/models/auto/auto_factory.py
  src/transformers/models/auto/modeling_auto.py
  tests/models/gemma3/test_modeling_gemma3.py
Labels: for patch

#36607 [ForCausalLMLoss] allow users to pass shifted labels
  src/transformers/loss/loss_utils.py
Labels: DeepSpeed

#36460 Fix fp16 ONNX export for RT-DETR and RT-DETRv2
  src/transformers/models/omdet_turbo/modeling_omdet_turbo.py
  src/transformers/models/rt_detr/modeling_rt_detr.py
  src/transformers/models/rt_detr_v2/modeling_rt_detr_v2.py
Labels: Vision

#35401 Add Prompt Depth Anything Model
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/prompt_depth_anything.md
  src/transformers/__init__.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/prompt_depth_anything/__init__.py
  src/transformers/models/prompt_depth_anything/configuration_prompt_depth_anything.py
  src/transformers/models/prompt_depth_anything/convert_prompt_depth_anything_to_hf.py
  src/transformers/models/prompt_depth_anything/image_processing_prompt_depth_anything.py
  src/transformers/models/prompt_depth_anything/modeling_prompt_depth_anything.py
  src/transformers/models/prompt_depth_anything/modular_prompt_depth_anything.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/models/prompt_depth_anything/__init__.py
  tests/models/prompt_depth_anything/test_image_processing_prompt_depth_anything.py
  tests/models/prompt_depth_anything/test_modeling_prompt_depth_anything.py
Labels: New model, Vision, run-slow

#36517 Make ViTPooler configurable
  src/transformers/modeling_flax_utils.py
  src/transformers/models/deit/configuration_deit.py
  src/transformers/models/deit/modeling_deit.py
  src/transformers/models/deit/modeling_tf_deit.py
  src/transformers/models/dpt/configuration_dpt.py
  src/transformers/models/dpt/modeling_dpt.py
  src/transformers/models/ijepa/configuration_ijepa.py
  src/transformers/models/ijepa/modeling_ijepa.py
  src/transformers/models/vit/configuration_vit.py
  src/transformers/models/vit/modeling_flax_vit.py
  src/transformers/models/vit/modeling_tf_vit.py
  src/transformers/models/vit/modeling_vit.py
Labels: Vision

#36907 Fix torch version guard at import
  src/transformers/cache_utils.py
Labels: for patch

#36918 [chameleon] fix num image token check
  src/transformers/models/chameleon/modeling_chameleon.py
  tests/generation/test_utils.py
  tests/models/chameleon/test_modeling_chameleon.py
  tests/models/mistral3/test_processor_mistral3.py
Labels: for patch

#36923 Fix pytorch defomr attn path
  src/transformers/models/deformable_detr/modeling_deformable_detr.py
  src/transformers/models/grounding_dino/modeling_grounding_dino.py
  src/transformers/models/omdet_turbo/modeling_omdet_turbo.py
  src/transformers/models/rt_detr/modeling_rt_detr.py
  src/transformers/models/rt_detr_v2/modeling_rt_detr_v2.py
Labels: Vision, for patch

#36917 Deprecate #36741 and map Causal to Conditional
  docs/source/en/model_doc/gemma3.md
  src/transformers/configuration_utils.py
  src/transformers/models/auto/modeling_auto.py
  tests/models/gemma3/test_modeling_gemma3.py
  tests/models/mistral3/test_processor_mistral3.py
Labels: for patch

#36780 Export for Phi4-mini
  tests/models/phi3/test_modeling_phi3.py
Labels: Text, torch export

#36847 [Utils] torch version checks optionally accept dev versions
  src/transformers/cache_utils.py
  src/transformers/pytorch_utils.py
  src/transformers/utils/import_utils.py
  tests/utils/test_cache_utils.py
Labels: for patch

#37001 Replace default split function with jnp.split() in flax models
  src/transformers/models/albert/modeling_flax_albert.py
  src/transformers/models/big_bird/modeling_flax_big_bird.py
  src/transformers/models/distilbert/modeling_flax_distilbert.py
  src/transformers/models/electra/modeling_flax_electra.py
  src/transformers/models/roformer/modeling_flax_roformer.py
Labels: Flax

#37027 Fix some typos about benchmark scripts.
  benchmark/README.md
  benchmark/benchmarks_entrypoint.py
  benchmark/llama.py
Labels: run-benchmark

#37080 [generate] beam search -- fix output cropping
  src/transformers/generation/utils.py
  tests/models/bart/test_modeling_bart.py
  tests/models/biogpt/test_modeling_biogpt.py
  tests/models/m2m_100/test_modeling_m2m_100.py
  tests/models/t5/test_modeling_t5.py
Labels: for patch

#37044 [Cache] rename dtype attribute 🚨 🚨
  src/transformers/cache_utils.py
Labels: for patch

#36486 Export T5 (encoder-decoder) to ExecuTorch
  src/transformers/integrations/executorch.py
  tests/models/t5/test_modeling_t5.py
Labels: ExecuTorch
