Repository huggingface/transformers, pull requests merged in 2025-07, with the labels that each got.

#39121 [qwen2-vl] fix FA2 inference
  src/transformers/modeling_flash_attention_utils.py
  src/transformers/models/glm4v/modeling_glm4v.py
  src/transformers/models/glm4v/modular_glm4v.py
  src/transformers/models/qwen2_5_omni/modeling_qwen2_5_omni.py
  src/transformers/models/qwen2_5_omni/modular_qwen2_5_omni.py
  src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py
  src/transformers/models/qwen2_5_vl/modular_qwen2_5_vl.py
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
  tests/models/qwen2_5_vl/test_modeling_qwen2_5_vl.py
  tests/models/qwen2_vl/test_modeling_qwen2_vl.py
Labels: for patch

#38850 fix: fixed wrong concatenation which made batching results wrong
  src/transformers/models/superglue/modeling_superglue.py
Labels: bug, Vision

#39152 when delaying optimizer creation only prepare the model
  src/transformers/trainer.py
Labels: for patch

#39184 Better return typehints for `from_pretrained`
  src/transformers/configuration_utils.py
  src/transformers/feature_extraction_utils.py
  src/transformers/modeling_utils.py
  src/transformers/models/clvp/configuration_clvp.py
  src/transformers/models/deprecated/jukebox/configuration_jukebox.py
  src/transformers/models/falcon/modeling_falcon.py
  src/transformers/models/qwen2_5_omni/configuration_qwen2_5_omni.py
  src/transformers/models/qwen2_5_omni/modular_qwen2_5_omni.py
  src/transformers/models/t5gemma/configuration_t5gemma.py
  src/transformers/models/t5gemma/modular_t5gemma.py
  src/transformers/processing_utils.py
Labels: typing

#39166 [bugfix] fix flash attention 2 unavailable error on Ascend NPU
  src/transformers/modeling_flash_attention_utils.py
Labels: for patch

#36625 Add Aimv2 model
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/aimv2.md
  src/transformers/models/__init__.py
  src/transformers/models/aimv2/__init__.py
  src/transformers/models/aimv2/configuration_aimv2.py
  src/transformers/models/aimv2/convert_aimv2_original_pytorch_to_hf.py
  src/transformers/models/aimv2/modeling_aimv2.py
  src/transformers/models/aimv2/modular_aimv2.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/siglip/modeling_siglip.py
  src/transformers/models/siglip2/modeling_siglip2.py
  tests/models/aimv2/__init__.py
  tests/models/aimv2/test_modeling_aimv2.py
  utils/check_repo.py
Labels: New model

#39253 Add trust_remote_code in LightGlueConfig
  src/transformers/models/lightglue/configuration_lightglue.py
  src/transformers/models/lightglue/modeling_lightglue.py
  src/transformers/models/lightglue/modular_lightglue.py
Labels: Vision

#39172 fix Glm4v batch videos forward
  src/transformers/models/glm4v/modeling_glm4v.py
  src/transformers/models/glm4v/modular_glm4v.py
  src/transformers/models/glm4v/processing_glm4v.py
  src/transformers/models/glm4v/video_processing_glm4v.py
  tests/models/glm4v/test_modeling_glm4v.py
  tests/models/glm4v/test_video_processing_glm4v.py
Labels: for patch

#37878 PerceptionLM
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/perception_lm.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/perception_lm/__init__.py
  src/transformers/models/perception_lm/configuration_perception_lm.py
  src/transformers/models/perception_lm/convert_perception_lm_weights_to_hf.py
  src/transformers/models/perception_lm/image_processing_perception_lm_fast.py
  src/transformers/models/perception_lm/modeling_perception_lm.py
  src/transformers/models/perception_lm/modular_perception_lm.py
  src/transformers/models/perception_lm/processing_perception_lm.py
  src/transformers/models/perception_lm/video_processing_perception_lm.py
  tests/models/perception_lm/__init__.py
  tests/models/perception_lm/test_image_processing_perception_lm.py
  tests/models/perception_lm/test_modeling_perception_lm.py
  tests/models/perception_lm/test_processor_perception_lm.py
  tests/models/perception_lm/test_video_processing_perception_lm.py
Labels: New model

#39422 refactor: remove `set_tracer_provider` and `set_meter_provider` calls
  src/transformers/utils/metrics.py
Labels: for patch

#39429 Add voxtral
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/voxtral.md
  src/transformers/audio_utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/processing_auto.py
  src/transformers/models/voxtral/__init__.py
  src/transformers/models/voxtral/configuration_voxtral.py
  src/transformers/models/voxtral/convert_voxtral_weights_to_hf.py
  src/transformers/models/voxtral/modeling_voxtral.py
  src/transformers/models/voxtral/modular_voxtral.py
  src/transformers/models/voxtral/processing_voxtral.py
  src/transformers/tokenization_mistral_common.py
  tests/models/voxtral/__init__.py
  tests/models/voxtral/test_modeling_voxtral.py
  tests/test_tokenization_mistral_common.py
Labels: New model

#39386 Update SAM/SAM HQ attention implementation + fix Cuda sync issues
  src/transformers/models/sam/modeling_sam.py
  src/transformers/models/sam_hq/modeling_sam_hq.py
  src/transformers/models/sam_hq/modular_sam_hq.py
  tests/models/sam_hq/test_modeling_sam_hq.py
Labels: run-slow

#35685 Mask2former & Maskformer Fast Image Processor
  docs/source/en/model_doc/mask2former.md
  docs/source/en/model_doc/maskformer.md
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/mask2former/__init__.py
  src/transformers/models/mask2former/image_processing_mask2former.py
  src/transformers/models/mask2former/image_processing_mask2former_fast.py
  src/transformers/models/mask2former/modular_mask2former.py
  src/transformers/models/maskformer/__init__.py
  src/transformers/models/maskformer/image_processing_maskformer.py
  src/transformers/models/maskformer/image_processing_maskformer_fast.py
  tests/models/mask2former/test_image_processing_mask2former.py
  tests/models/maskformer/test_image_processing_maskformer.py
Labels: Vision, Processing

#39313 Fix DAC integration tests and checkpoint conversion.
  src/transformers/models/dac/convert_dac_checkpoint.py
  tests/models/dac/test_modeling_dac.py
Labels: Audio

#39621 Fix EfficientLoFTR model id in tests
  tests/models/efficientloftr/test_modeling_efficientloftr.py
Labels: Vision

#39572 fix(voxtral): correct typo in apply_transcription_request
  docs/source/en/model_doc/voxtral.md
  src/transformers/models/voxtral/processing_voxtral.py
  tests/models/voxtral/test_modeling_voxtral.py
Labels: Audio

#39671 Fix ModernBERT Decoder model
  src/transformers/models/modernbert_decoder/modeling_modernbert_decoder.py
  src/transformers/models/modernbert_decoder/modular_modernbert_decoder.py
Labels: bug

#39688 fix missing model._tp_size from ep refactor
  src/transformers/integrations/tensor_parallel.py
Labels: for patch

#39693 PATCH: add back n-dim device-mesh + fix tp trainer saving
  src/transformers/modeling_utils.py
  src/transformers/trainer.py
Labels: for patch

#39732 Fix Layer device placement in Caches
  src/transformers/cache_utils.py
Labels: for patch

#39676 Fix cache-related tests
  src/transformers/generation/utils.py
  src/transformers/models/kyutai_speech_to_text/modeling_kyutai_speech_to_text.py
  src/transformers/models/kyutai_speech_to_text/modular_kyutai_speech_to_text.py
  src/transformers/models/musicgen/modeling_musicgen.py
  src/transformers/models/musicgen_melody/modeling_musicgen_melody.py
  src/transformers/models/rag/modeling_rag.py
  src/transformers/models/roformer/modeling_roformer.py
  src/transformers/models/superglue/modeling_superglue.py
  tests/models/llava_next/test_modeling_llava_next.py
  tests/models/llava_next_video/test_modeling_llava_next_video.py
  tests/models/qwen2_5_omni/test_modeling_qwen2_5_omni.py
  tests/models/qwen2_5_vl/test_modeling_qwen2_5_vl.py
  tests/models/qwen2_vl/test_modeling_qwen2_vl.py
  tests/pipelines/test_pipelines_image_text_to_text.py
Labels: for patch

#39728 Fix mamba regression
  src/transformers/models/falcon_mamba/configuration_falcon_mamba.py
  src/transformers/models/falcon_mamba/modular_falcon_mamba.py
  src/transformers/models/mamba/modeling_mamba.py
Labels: for patch

#39750 [modenbert] fix regression
  src/transformers/models/modernbert/modeling_modernbert.py
  src/transformers/models/modernbert/modular_modernbert.py
  tests/models/modernbert/test_modeling_modernbert.py
Labels: for patch

#39660 [docs] Ko doc fixes after toc update
  .github/workflows/build_documentation.yml
  .github/workflows/build_pr_documentation.yml
  docs/source/ko/_toctree.yml
  docs/source/ko/accelerator_selection.md
  docs/source/ko/attention.md
  docs/source/ko/autoclass_tutorial.md
  docs/source/ko/bertology.md
  docs/source/ko/big_models.md
  docs/source/ko/create_a_model.md
  docs/source/ko/model_summary.md
  docs/source/ko/multilingual.md
  docs/source/ko/perf_train_tpu_tf.md
  docs/source/ko/performance.md
  docs/source/ko/preprocessing.md
  docs/source/ko/sagemaker.md
  docs/source/ko/task_summary.md
  docs/source/ko/tasks_explained.md
  docs/source/ko/tf_xla.md
Labels: for patch

#37483 Add callback to monitor progress in whisper transcription
  src/transformers/models/whisper/generation_whisper.py
Labels: Audio, Whisper
