Repository huggingface/transformers, pull requests merged in 2025-10, with the labels that each got.

#41214 [V5] Remove deprecated transformers.onnx
  docs/source/en/_toctree.yml
  docs/source/en/main_classes/onnx.md
  setup.py
  src/transformers/dependency_versions_table.py
  src/transformers/onnx/__init__.py
  src/transformers/onnx/__main__.py
  src/transformers/onnx/convert.py
  src/transformers/onnx/features.py
  utils/not_doctested.txt
Labels: for_v5?

#41267 Remove SageMakerTrainer
  src/transformers/__init__.py
  src/transformers/sagemaker/__init__.py
  src/transformers/sagemaker/trainer_sm.py
  src/transformers/sagemaker/training_args_sm.py
  tests/sagemaker/README.md
  tests/sagemaker/scripts/pytorch/run_glue_model_parallelism.py
  tests/sagemaker/scripts/tensorflow/requirements.txt
  utils/not_doctested.txt
Labels: for_v5?

#41237 Fix binding of video frames to video placeholder in `InternVL` model
  src/transformers/models/internvl/processing_internvl.py
  tests/models/internvl/test_processing_internvl.py
Labels: run-slow

#41268 🚨 Bump to Python 3.10 and rework how we check 3rd-party libraries existence
  setup.py
  src/transformers/__init__.py
  src/transformers/dependency_versions_table.py
  src/transformers/file_utils.py
  src/transformers/integrations/flex_attention.py
  src/transformers/models/deprecated/jukebox/tokenization_jukebox.py
  src/transformers/testing_utils.py
  src/transformers/utils/__init__.py
  src/transformers/utils/generic.py
  src/transformers/utils/hub.py
  src/transformers/utils/import_utils.py
  tests/generation/test_utils.py
Labels: for_v5?

#33380 Update from pretrained error when loading
  src/transformers/modeling_utils.py
  src/transformers/models/deepseek_v3/configuration_deepseek_v3.py
  tests/utils/test_modeling_utils.py
Labels: Core: Modeling, for_v5?

#41248 [`v5`] Sync Bert and Bart eager attention
  src/transformers/models/albert/modeling_albert.py
  src/transformers/models/bart/modeling_bart.py
  src/transformers/models/bert/modeling_bert.py
  src/transformers/models/bert_generation/modeling_bert_generation.py
  src/transformers/models/bigbird_pegasus/modeling_bigbird_pegasus.py
  src/transformers/models/biogpt/modeling_biogpt.py
  src/transformers/models/blenderbot/modeling_blenderbot.py
  src/transformers/models/blenderbot_small/modeling_blenderbot_small.py
  src/transformers/models/bridgetower/modeling_bridgetower.py
  src/transformers/models/camembert/modeling_camembert.py
  src/transformers/models/data2vec/modeling_data2vec_audio.py
  src/transformers/models/data2vec/modeling_data2vec_text.py
  src/transformers/models/distilbert/modeling_distilbert.py
  src/transformers/models/electra/modeling_electra.py
  src/transformers/models/ernie/modeling_ernie.py
  src/transformers/models/esm/modeling_esm.py
  src/transformers/models/evolla/modeling_evolla.py
  src/transformers/models/florence2/modeling_florence2.py
  src/transformers/models/hubert/modeling_hubert.py
  src/transformers/models/informer/modeling_informer.py
  src/transformers/models/m2m_100/modeling_m2m_100.py
  src/transformers/models/marian/modeling_marian.py
  src/transformers/models/mbart/modeling_mbart.py
  src/transformers/models/mobilebert/modeling_mobilebert.py
  src/transformers/models/musicgen/modeling_musicgen.py
  src/transformers/models/musicgen_melody/modeling_musicgen_melody.py
  src/transformers/models/nllb_moe/modeling_nllb_moe.py
  src/transformers/models/patchtsmixer/modeling_patchtsmixer.py
  src/transformers/models/patchtst/modeling_patchtst.py
  src/transformers/models/pegasus/modeling_pegasus.py
  src/transformers/models/pegasus_x/modeling_pegasus_x.py
  src/transformers/models/plbart/modeling_plbart.py
  src/transformers/models/roberta/modeling_roberta.py
  src/transformers/models/roberta_prelayernorm/modeling_roberta_prelayernorm.py
  src/transformers/models/roc_bert/modeling_roc_bert.py
  src/transformers/models/sew/modeling_sew.py
  src/transformers/models/speech_to_text/modeling_speech_to_text.py
  src/transformers/models/time_series_transformer/modeling_time_series_transformer.py
  src/transformers/models/unispeech/modeling_unispeech.py
  src/transformers/models/unispeech_sat/modeling_unispeech_sat.py
  src/transformers/models/wav2vec2/modeling_wav2vec2.py
  src/transformers/models/xlm_roberta/modeling_xlm_roberta.py
  src/transformers/models/xlm_roberta_xl/modeling_xlm_roberta_xl.py
  src/transformers/models/xmod/modeling_xmod.py
Labels: for_v5?
