Repository huggingface/transformers, pull requests merged in 2025-02, with the labels that each got.

#35998 Update Granite Vision Model Path / Tests
  docs/source/en/model_doc/granitevision.md
  tests/models/llava_next/test_modeling_llava_next.py
Labels: run-slow

#35979 Fix custom kernel for DeformableDetr, RT-Detr, GroindingDINO, OmDet-Turbo in Pytorch 2.6.0
  src/transformers/kernels/deformable_detr/cuda/ms_deform_attn_cuda.cu
  src/transformers/kernels/deformable_detr/cuda/ms_deform_attn_cuda.cuh
  src/transformers/kernels/deformable_detr/cuda/ms_deform_im2col_cuda.cuh
  src/transformers/kernels/deformable_detr/ms_deform_attn.h
Labels: Vision

#36044 Paligemma: fix generation with Gemma2
  src/transformers/models/llava/modeling_llava.py
  src/transformers/models/llava_next/modeling_llava_next.py
  src/transformers/models/llava_next_video/modeling_llava_next_video.py
  src/transformers/models/llava_next_video/modular_llava_next_video.py
  src/transformers/models/llava_onevision/modeling_llava_onevision.py
  src/transformers/models/paligemma/modeling_paligemma.py
  src/transformers/models/video_llava/modeling_video_llava.py
  src/transformers/models/vipllava/modeling_vipllava.py
  tests/models/paligemma2/__init__.py
  tests/models/paligemma2/test_modeling_paligemma2.py
Labels: for patch

#34773 Adding RTDETRv2
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/rt_detr_v2.md
  src/transformers/__init__.py
  src/transformers/loss/loss_rt_detr.py
  src/transformers/loss/loss_utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/rt_detr/modeling_rt_detr.py
  src/transformers/models/rt_detr_v2/__init__.py
  src/transformers/models/rt_detr_v2/configuration_rt_detr_v2.py
  src/transformers/models/rt_detr_v2/convert_rt_detr_v2_weights_to_hf.py
  src/transformers/models/rt_detr_v2/modeling_rt_detr_v2.py
  src/transformers/models/rt_detr_v2/modular_rt_detr_v2.py
  src/transformers/utils/dummy_pt_objects.py
  tests/models/rt_detr_v2/__init__.py
  tests/models/rt_detr_v2/test_modeling_rt_detr_v2.py
  utils/check_config_attributes.py
Labels: New model, Vision, run-slow, Modular

#34583 Add support for Apple's Depth-Pro
  docs/source/en/_toctree.yml
  docs/source/en/index.md
  docs/source/en/model_doc/depth_pro.md
  docs/source/en/perf_infer_gpu_one.md
  src/transformers/__init__.py
  src/transformers/image_processing_utils_fast.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/image_processing_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/depth_pro/__init__.py
  src/transformers/models/depth_pro/configuration_depth_pro.py
  src/transformers/models/depth_pro/convert_depth_pro_weights_to_hf.py
  src/transformers/models/depth_pro/image_processing_depth_pro.py
  src/transformers/models/depth_pro/image_processing_depth_pro_fast.py
  src/transformers/models/depth_pro/modeling_depth_pro.py
  src/transformers/models/dinov2/configuration_dinov2.py
  src/transformers/models/dinov2/modeling_dinov2.py
  src/transformers/models/dinov2/modeling_flax_dinov2.py
  src/transformers/utils/dummy_pt_objects.py
  src/transformers/utils/dummy_torchvision_objects.py
  src/transformers/utils/dummy_vision_objects.py
  tests/models/depth_pro/__init__.py
  tests/models/depth_pro/test_image_processing_depth_pro.py
  tests/models/depth_pro/test_modeling_depth_pro.py
Labels: New model, Vision

#35662 Fix CI issues
  tests/models/bamba/test_modeling_bamba.py
Labels: run-slow

#36098 Remove loading custom kernel for RT-DETRv2
  src/transformers/models/rt_detr_v2/configuration_rt_detr_v2.py
  src/transformers/models/rt_detr_v2/modeling_rt_detr_v2.py
  src/transformers/models/rt_detr_v2/modular_rt_detr_v2.py
Labels: cleanup, Vision

#35837 Optimize Qwen2VL vision model by precomputing cos/sin embeds before ViT blocks
  src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py
  src/transformers/models/qwen2_5_vl/modular_qwen2_5_vl.py
  src/transformers/models/qwen2_vl/modeling_qwen2_vl.py
Labels: optimization, Multimodal

#35700 Uniformize OwlViT and Owlv2 processors
  src/transformers/models/owlv2/processing_owlv2.py
  src/transformers/models/owlvit/processing_owlvit.py
  tests/models/owlv2/test_processor_owlv2.py
  tests/models/owlvit/test_processor_owlvit.py
Labels: run-slow

#35138 addressing the issue #34611 to make FlaxDinov2 compatible with any batch size
  src/transformers/models/dinov2/modeling_flax_dinov2.py
  tests/models/dinov2/test_modeling_flax_dinov2.py
Labels: Flax

#36397 Fix integration tests for SAM
  tests/models/sam/test_modeling_sam.py
Labels: Tests, Vision

#36376 [CLI] add import guards
  src/transformers/commands/chat.py
  src/transformers/utils/__init__.py
  src/transformers/utils/import_utils.py
Labels: for patch

#36369 Removed numpy conversion to correctly convert PIL image to rgb
  src/transformers/models/sam/image_processing_sam.py
Labels: bug, Vision, Processing

#36335 Update form pretrained to make TP a first class citizen
  src/transformers/modeling_utils.py
  src/transformers/models/aria/modeling_aria.py
  src/transformers/models/bamba/modeling_bamba.py
  src/transformers/models/diffllama/modeling_diffllama.py
  src/transformers/models/emu3/modeling_emu3.py
  src/transformers/models/falcon/modeling_falcon.py
  src/transformers/models/gemma/modeling_gemma.py
  src/transformers/models/gemma2/modeling_gemma2.py
  src/transformers/models/glm/modeling_glm.py
  src/transformers/models/gpt_neox/modeling_gpt_neox.py
  src/transformers/models/gpt_neox_japanese/modeling_gpt_neox_japanese.py
  src/transformers/models/granite/modeling_granite.py
  src/transformers/models/granitemoe/modeling_granitemoe.py
  src/transformers/models/granitemoeshared/modeling_granitemoeshared.py
  src/transformers/models/helium/modeling_helium.py
  src/transformers/models/jetmoe/modeling_jetmoe.py
  src/transformers/models/llama/modeling_llama.py
  src/transformers/models/mimi/modeling_mimi.py
  src/transformers/models/mistral/modeling_mistral.py
  src/transformers/models/mixtral/modeling_mixtral.py
  src/transformers/models/modernbert/modeling_modernbert.py
  src/transformers/models/moonshine/modeling_moonshine.py
  src/transformers/models/moshi/modeling_moshi.py
  src/transformers/models/nemotron/modeling_nemotron.py
  src/transformers/models/olmo/modeling_olmo.py
  src/transformers/models/olmo2/modeling_olmo2.py
  src/transformers/models/olmoe/modeling_olmoe.py
  src/transformers/models/persimmon/modeling_persimmon.py
  src/transformers/models/phi/modeling_phi.py
  src/transformers/models/qwen2/modeling_qwen2.py
  src/transformers/models/qwen2_moe/modeling_qwen2_moe.py
  src/transformers/models/stablelm/modeling_stablelm.py
  src/transformers/models/starcoder2/modeling_starcoder2.py
  src/transformers/models/zamba2/modeling_zamba2.py
  src/transformers/pytorch_utils.py
  tests/utils/test_modeling_utils.py
Labels: Tensor Parallel

#31828 [GroundingDino] Fix grounding dino loss 🚨
  src/transformers/loss/loss_grounding_dino.py
  src/transformers/loss/loss_utils.py
  src/transformers/models/grounding_dino/modeling_grounding_dino.py
  tests/models/grounding_dino/test_modeling_grounding_dino.py
Labels: run-slow
