Repository huggingface/transformers, pull requests merged in 2025-05, with the labels that each got.

#36719 Add CSM model
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/csm.md
  src/transformers/audio_utils.py
  src/transformers/generation/stopping_criteria.py
  src/transformers/generation/utils.py
  src/transformers/loss/loss_utils.py
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/csm/__init__.py
  src/transformers/models/csm/configuration_csm.py
  src/transformers/models/csm/convert_csm.py
  src/transformers/models/csm/generation_csm.py
  src/transformers/models/csm/modeling_csm.py
  src/transformers/models/csm/modular_csm.py
  src/transformers/models/csm/processing_csm.py
  src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
  src/transformers/models/janus/modeling_janus.py
  src/transformers/models/janus/modular_janus.py
  src/transformers/models/mimi/modeling_mimi.py
  src/transformers/models/qwen2_5_omni/modeling_qwen2_5_omni.py
  src/transformers/models/qwen2_5_omni/modular_qwen2_5_omni.py
  src/transformers/processing_utils.py
  tests/generation/test_utils.py
  tests/models/csm/__init__.py
  tests/models/csm/test_modeling_csm.py
  tests/models/csm/test_processor_csm.py
  tests/test_modeling_common.py
  utils/check_repo.py
Labels: New model, Audio

#38015 Fix linalg.norm for CovnNextV2
  src/transformers/models/convnextv2/modeling_convnextv2.py
Labels: bug

#38014 fix(conversion): Fix size mismatch error during TF->PT model loading
  src/transformers/modeling_tf_pytorch_utils.py
  tests/utils/test_modeling_utils.py
Labels: TensorFlow

#38294 Fix tp error when torch distributed is already initialized
  src/transformers/integrations/tensor_parallel.py
Labels: for patch

#38365 [paligemma] fix processor with suffix
  src/transformers/models/paligemma/processing_paligemma.py
  tests/models/paligemma/test_processor_paligemma.py
Labels: for patch

#38374 [video utils] group and reorder by number of frames
  src/transformers/video_utils.py
  tests/utils/test_video_utils.py
Labels: for patch
