Repository huggingface/transformers, pull requests merged in 2025-09, with the labels that each got.

#40638 fix pipeline dtype
  src/transformers/pipelines/__init__.py
Labels: for patch

#40668 Fix backward compatibility with accelerate in Trainer
  src/transformers/trainer.py
Labels: for patch

#40609 Fix broken Llama4 accuracy in MoE part
  src/transformers/models/llama4/modeling_llama4.py
Labels: for patch

#40628 Fixing the call to kernelize
  src/transformers/modeling_utils.py
Labels: kernels

#40824 Fix getter regression
  src/transformers/modeling_utils.py
  tests/utils/test_modeling_utils.py
Labels: for patch

#40778 Add Olmo3 model
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/olmo3.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/olmo3/__init__.py
  src/transformers/models/olmo3/configuration_olmo3.py
  src/transformers/models/olmo3/convert_olmo3_weights_to_hf.py
  src/transformers/models/olmo3/modeling_olmo3.py
  src/transformers/models/olmo3/modular_olmo3.py
  tests/models/olmo3/__init__.py
  tests/models/olmo3/test_modeling_olmo3.py
Labels: New model

#40921 Add FlexOlmo model
  docs/source/en/_toctree.yml
  docs/source/en/model_doc/flex_olmo.md
  src/transformers/models/__init__.py
  src/transformers/models/auto/configuration_auto.py
  src/transformers/models/auto/modeling_auto.py
  src/transformers/models/auto/tokenization_auto.py
  src/transformers/models/flex_olmo/__init__.py
  src/transformers/models/flex_olmo/configuration_flex_olmo.py
  src/transformers/models/flex_olmo/modeling_flex_olmo.py
  src/transformers/models/flex_olmo/modular_flex_olmo.py
  tests/models/flex_olmo/__init__.py
  tests/models/flex_olmo/test_modeling_flex_olmo.py
Labels: New model

#41083 Fix attention sink implementation in flex attention
  docs/source/en/model_doc/gpt_oss.md
  src/transformers/integrations/flex_attention.py
Labels: flex attention
